// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// c_IF_fav_censoring
DataFrame c_IF_fav_censoring(CharacterVector arm, NumericVector time, IntegerVector status, double lambda_val);
RcppExport SEXP _infuse_c_IF_fav_censoring(SEXP armSEXP, SEXP timeSEXP, SEXP statusSEXP, SEXP lambda_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type arm(armSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type status(statusSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_val(lambda_valSEXP);
    rcpp_result_gen = Rcpp::wrap(c_IF_fav_censoring(arm, time, status, lambda_val));
    return rcpp_result_gen;
END_RCPP
}
// c_IF_fav_no_censoring
DataFrame c_IF_fav_no_censoring(CharacterVector arm, NumericVector time, double lambda_val);
RcppExport SEXP _infuse_c_IF_fav_no_censoring(SEXP armSEXP, SEXP timeSEXP, SEXP lambda_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type arm(armSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_val(lambda_valSEXP);
    rcpp_result_gen = Rcpp::wrap(c_IF_fav_no_censoring(arm, time, lambda_val));
    return rcpp_result_gen;
END_RCPP
}
// c_ecdf_plus
List c_ecdf_plus(NumericVector x, Nullable<IntegerVector> xs);
RcppExport SEXP _infuse_c_ecdf_plus(SEXP xSEXP, SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type xs(xsSEXP);
    rcpp_result_gen = Rcpp::wrap(c_ecdf_plus(x, xs));
    return rcpp_result_gen;
END_RCPP
}
// c_ecdf_predict
NumericVector c_ecdf_predict(NumericVector z, NumericVector x_sorted, NumericVector p_sorted);
RcppExport SEXP _infuse_c_ecdf_predict(SEXP zSEXP, SEXP x_sortedSEXP, SEXP p_sortedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_sorted(x_sortedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_sorted(p_sortedSEXP);
    rcpp_result_gen = Rcpp::wrap(c_ecdf_predict(z, x_sorted, p_sorted));
    return rcpp_result_gen;
END_RCPP
}
// c_ecdf_predict_less
NumericVector c_ecdf_predict_less(NumericVector z, NumericVector x_sorted, NumericVector p_sorted);
RcppExport SEXP _infuse_c_ecdf_predict_less(SEXP zSEXP, SEXP x_sortedSEXP, SEXP p_sortedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_sorted(x_sortedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_sorted(p_sortedSEXP);
    rcpp_result_gen = Rcpp::wrap(c_ecdf_predict_less(z, x_sorted, p_sorted));
    return rcpp_result_gen;
END_RCPP
}
// c_extendtail
List c_extendtail(NumericVector uni, NumericVector w, double mlesi, double mlesh, double extra_n);
RcppExport SEXP _infuse_c_extendtail(SEXP uniSEXP, SEXP wSEXP, SEXP mlesiSEXP, SEXP mleshSEXP, SEXP extra_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type uni(uniSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type mlesi(mlesiSEXP);
    Rcpp::traits::input_parameter< double >::type mlesh(mleshSEXP);
    Rcpp::traits::input_parameter< double >::type extra_n(extra_nSEXP);
    rcpp_result_gen = Rcpp::wrap(c_extendtail(uni, w, mlesi, mlesh, extra_n));
    return rcpp_result_gen;
END_RCPP
}
// c_fav
double c_fav(CharacterVector arm, NumericVector time, IntegerVector status, double lambda_val);
RcppExport SEXP _infuse_c_fav(SEXP armSEXP, SEXP timeSEXP, SEXP statusSEXP, SEXP lambda_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type arm(armSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type status(statusSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_val(lambda_valSEXP);
    rcpp_result_gen = Rcpp::wrap(c_fav(arm, time, status, lambda_val));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_infuse_c_IF_fav_censoring", (DL_FUNC) &_infuse_c_IF_fav_censoring, 4},
    {"_infuse_c_IF_fav_no_censoring", (DL_FUNC) &_infuse_c_IF_fav_no_censoring, 3},
    {"_infuse_c_ecdf_plus", (DL_FUNC) &_infuse_c_ecdf_plus, 2},
    {"_infuse_c_ecdf_predict", (DL_FUNC) &_infuse_c_ecdf_predict, 3},
    {"_infuse_c_ecdf_predict_less", (DL_FUNC) &_infuse_c_ecdf_predict_less, 3},
    {"_infuse_c_extendtail", (DL_FUNC) &_infuse_c_extendtail, 5},
    {"_infuse_c_fav", (DL_FUNC) &_infuse_c_fav, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_infuse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
