#' Harvest Win/Loss Influence-Based Results
#'
#' @description
#' The primary engine for gathering analytic results from a \code{sow} object.
#' This function passes weighted ECDF data to the C++ inference engine to
#' calculate point estimates and influence functions for Favorable (wins) and
#' Unfavorable (losses) outcomes.
#'
#' @param fit An S3 object of class \code{"sow"} generated by the \code{sow()} function.
#' @return A list of class \code{"harvest"} containing three tidy data frames:
#' \itemize{
#'   \item \code{theta}: Point estimates (\code{f} for Favorable, \code{u} for Unfavorable)
#'     paired with the corresponding \code{Variable} name.
#'   \item \code{IF_x}: Influence function values for the \bold{Treated} group,
#'     including \code{ID}, censoring indicators (\code{ce}), and sample weights.
#'   \item \code{IF_y}: Influence function values for the \bold{Control} group,
#'     structured identically to \code{IF_x}.
#' }
#'
#' @details
#' The function acts as an interface to the C++ backend. It handles the
#' directionality of the clinical benefit:
#' \itemize{
#'   \item If an outcome is marked as \code{good = "high"}, the "Favorable"
#'     estimate is derived from the standard favorable influence function.
#'   \item If an outcome is marked as \code{good = "low"}, the definitions
#'     are swapped internally so that \code{f} always represents the clinically
#'     beneficial direction.
#' }
#' The influence functions are re-sorted internally to ensure the output
#' matches the original row order of the data provided to \code{sow()}.
#'
#'
#' @examples
#' # ---------------------------------------------------------
#' # Example 1: Survival Data (Ipilimumab)
#' # ---------------------------------------------------------
#' data(ipilimumab)
#' # Higher time is "good" for Progression-Free Survival
#' fit <- sow(Surv(time, event) ~ arm,
#'                  data = ipilimumab,
#'                  treated = "ipilimumab",
#'                  good = "high")
#'
#' h <- harvest(fit,lambda = 6)
#' print(h)
#' summary(h)
#' plot(h,metric="netb",type = "estimate")
#'
#' # ---------------------------------------------------------
#' # Example 2: Continuous Data (Obstetrics)
#' # ---------------------------------------------------------
#' data(obstetrics)
#' # High birthweight is generally considered "good"
#' fit <- sow(Birthweight ~ Group,
#'                 data = obstetrics,
#'                 treated = "T",
#'                 good = "high")
#'
#' h <- harvest(fit,lambda = 500)
#' print(h)
#' summary(h)
#' plot(h,metric="wr",type = "influence")
#'
#' # ---------------------------------------------------------
#' # Example 3: Longitudinal Binary Data (Respiratory)
#' # ---------------------------------------------------------
#' data(respiratory)
#' # We analyze status at the final visit (Visit 4)
#' resp_v4 <- respiratory[respiratory$visit == 4, ]
#' sown_resp <- sow(outcome ~ treat,
#'                  data = resp_v4,
#'                  treated = "A",
#'                  good = "high")
#'
#' h <- harvest(fit,lambda = 0.5)
#' print(h)
#' summary(h)
#' plot(h,metric="wr",type = "influence")
#'
#' # ---------------------------------------------------------
#' # Example 4: Multiple Outcomes (Epilepsy)
#' # ---------------------------------------------------------
#' data(epilepsy)
#' # Looking at seizure rate at Period 4. Lower rate is "good".
#' epi_v4 <- epilepsy[epilepsy$period == 4, ]
#' sown_epi <- sow(seizure.rate ~ treatment,
#'                 data = epi_v4,
#'                 treated = "Progabide",
#'                 good = "low")
#'
#' h <- harvest(fit,lambda = 15)
#' print(h)
#' summary(h)
#' plot(h,metric="wr",type = "influence")
#'
#' @export
harvest <- function(fit){

  if (!inherits(fit, "sow")) stop("Input must be a 'sow' object.")

  responses <- names(fit$Variables)
  n_outcomes <- length(responses)

  ## --- 1. Handle Lambda Recycling ---
  #if (length(lambda) < n_outcomes) {
  #  warning(sprintf(
  #    "The 'lambda' vector length (%d) is less than the number of outcomes (%d). Carrying forward the last value.",
  #    length(lambda), n_outcomes
  #  ))
  #  lambda <- c(lambda, rep(tail(lambda, 1), n_outcomes - length(lambda)))
  #}

  # --- 2. Process Outcomes ---
  # Pre-allocate lists for efficiency
  theta_list <- vector("list", n_outcomes)
  ifx_list   <- vector("list", n_outcomes)
  ify_list   <- vector("list", n_outcomes)

  for (k in seq_along(responses)) {
    var_name <- responses[k]
    l <- fit$Variables[[var_name]]
    lam_k <- l$lambda

    # Pre-calculate sorting indices
    orx <- order(l$x)
    ory <- order(l$y)

    # Back-sorting indices to return to original data order
    rev_orx <- order(orx)
    rev_ory <- order(ory)

    # Determine function calls based on "good" direction
    # If high is good: Favorable = fav function, Unfavorable = unfav function
    # If low is good:  Favorable = unfav function, Unfavorable = fav function
    if (l$good == "high") {
      res_f <- c_influence_favorable(l$x[orx], l$y[ory], l$x_uni, l$y_uni, l$x_w, l$y_w, lam_k)
      res_u <- c_influence_unfavorable(l$x[orx], l$y[ory], l$x_uni, l$y_uni, l$x_w, l$y_w, lam_k)
    } else {
      res_f <- c_influence_unfavorable(l$x[orx], l$y[ory], l$x_uni, l$y_uni, l$x_w, l$y_w, lam_k)
      res_u <- c_influence_favorable(l$x[orx], l$y[ory], l$x_uni, l$y_uni, l$x_w, l$y_w, lam_k)
    }

    # Store Point Estimates
    theta_list[[k]] <- data.frame(
      f = res_f$theta,
      u = res_u$theta,
      Variable = var_name
    )

    # Store Influence Functions for Treated (x)
    ifx_list[[k]] <- data.frame(
      ID = fit$xid,
      ce = l$xs,
      weights = l$x_weights,
      f = res_f$IF_x[rev_orx],
      u = res_u$IF_x[rev_orx],
      Variable = var_name
    )

    # Store Influence Functions for Control (y)
    ify_list[[k]] <- data.frame(
      ID = fit$yid,
      ce = l$ys,
      weights = l$y_weights,
      f = res_f$IF_y[rev_ory],
      u = res_u$IF_y[rev_ory],
      Variable = var_name
    )
  }

  # --- 3. Final Assembly ---
  var_types <- sapply(fit$Variables, function(v) v$type)

  structure(
    list(
      theta = do.call(rbind, theta_list),
      IF_x  = do.call(rbind, ifx_list),
      IF_y  = do.call(rbind, ify_list)
    ),
    class = "harvest",
    var_types = var_types
  )


}
