#' Harvest Win/Loss Influence-Based Results
#'
#' @description
#' The primary engine for gathering analytic results from a \code{sow} object.
#' This function passes weighted ECDF data to the C++ inference engine to
#' calculate point estimates and influence functions for Wins, Losses,
#' Net Benefit, and Win Ratios.
#'
#' @param fit An S3 object of class \code{"sow"} generated by the \code{sow()} function.
#' @param lambda A numeric vector of thresholds defining the margin of clinical
#'   importance for each outcome. Recycled if shorter than the number of outcomes.
#'
#' @return A list containing three data frames:
#' \itemize{
#'   \item \code{theta}: Point estimates (Favorable, Unfavorable, Net Benefit, Win Ratio) for each outcome.
#'   \item \code{IF_x}: Influence function values and metadata for the Treated group.
#'   \item \code{IF_y}: Influence function values and metadata for the Control group.
#' }
#'
#' @details
#' The function calculates:
#' \itemize{
#'   \item \bold{Favorable (f):} Probability the treated group wins.
#'   \item \bold{Unfavorable (u):} Probability the treated group loses.
#'   \item \bold{Net Benefit (n):} \eqn{f - u}.
#'   \item \bold{Win Ratio (w):} \eqn{\log(f) - \log(u)} (modeled in log-space for influence).
#' }
#'
#' @examples
#' # ---------------------------------------------------------
#' # Example 1: Survival Data (Ipilimumab)
#' # ---------------------------------------------------------
#' data(ipilimumab)
#' # Higher time is "good" for Progression-Free Survival
#' fit <- sow(Surv(time, event) ~ arm,
#'                  data = ipilimumab,
#'                  treated = "ipilimumab",
#'                  good = "high")
#'
#' h <- harvest(fit,lambda = 6)
#' print(h)
#' summary(h)
#' plot(h,metric="netb",type = "estimate")
#'
#' # ---------------------------------------------------------
#' # Example 2: Continuous Data (Obstetrics)
#' # ---------------------------------------------------------
#' data(obstetrics)
#' # High birthweight is generally considered "good"
#' fit <- sow(Birthweight ~ Group,
#'                 data = obstetrics,
#'                 treated = "T",
#'                 good = "high")
#'
#' h <- harvest(fit,lambda = 500)
#' print(h)
#' summary(h)
#' plot(h,metric="wr",type = "influence")
#'
#' # ---------------------------------------------------------
#' # Example 3: Longitudinal Binary Data (Respiratory)
#' # ---------------------------------------------------------
#' data(respiratory)
#' # We analyze status at the final visit (Visit 4)
#' resp_v4 <- respiratory[respiratory$visit == 4, ]
#' sown_resp <- sow(outcome ~ treat,
#'                  data = resp_v4,
#'                  treated = "A",
#'                  good = "high")
#'
#' h <- harvest(fit,lambda = 0.5)
#' print(h)
#' summary(h)
#' plot(h,metric="wr",type = "influence")
#'
#' # ---------------------------------------------------------
#' # Example 4: Multiple Outcomes (Epilepsy)
#' # ---------------------------------------------------------
#' data(epilepsy)
#' # Looking at seizure rate at Period 4. Lower rate is "good".
#' epi_v4 <- epilepsy[epilepsy$period == 4, ]
#' sown_epi <- sow(seizure.rate ~ treatment,
#'                 data = epi_v4,
#'                 treated = "Progabide",
#'                 good = "low")
#'
#' h <- harvest(fit,lambda = 15)
#' print(h)
#' summary(h)
#' plot(h,metric="wr",type = "influence")
#'
#' @export
harvest <- function(fit,lambda=0.5){

  if (!inherits(fit, "sow")) stop("Input must be a 'sow' object.")

  n_outcomes <- length(fit$Variables)

  # Check if 'good' vector is too short
  if (length(lambda) < n_outcomes) {
    warning(paste0("The 'lambda' vector length (", length(lambda),
                   ") is less than the number of outcomes (", n_outcomes,
                   "). Carrying forward the last value of 'lambda'."))

    # Fill the 'good' vector to match the length of outcomes
    # This repeats the last element until it matches n_outcomes
    lambda <- c(lambda, rep(tail(lambda, 1), n_outcomes - length(lambda)))
  }

  Responses <- names(fit$Variables)
  temp <- lapply(1:length(Responses),function(k){
    xxx <- Responses[k]
    l <- fit$Variables[[xxx]]

    orx <- order(l$x)
    ory <- order(l$y)

    ss_x <- sum(l$xs,na.rm=TRUE)
    ss_y <- sum(l$ys,na.rm=TRUE)

    ## FAVORABLE
    if (l$good=="high") {
      ooo1 <- c_influence_favorable(l$x[orx],l$y[ory],l$x_uni,l$y_uni,l$x_w,l$y_w,lambda[k])
    } else {
      ooo1 <- c_influence_unfavorable(l$x[orx],l$y[ory],l$x_uni,l$y_uni,l$x_w,l$y_w,lambda[k])
    }
    IF_x <- data.frame(ID = fit$xid,ce=l$xs,weights=l$x_weights,f = ooo1$IF_x[order(orx)])
    IF_y <- data.frame(ID = fit$yid,ce=l$ys,weights=l$y_weights,f = ooo1$IF_y[order(ory)])
    theta <- data.frame(f = ooo1$theta)

    ## UNFAVORABLE
    if (l$good=="high") {
      ooo2 <- c_influence_unfavorable(l$x[orx],l$y[ory],l$x_uni,l$y_uni,l$x_w,l$y_w,lambda[k])
    } else {
      ooo2 <- c_influence_favorable(l$x[orx],l$y[ory],l$x_uni,l$y_uni,l$x_w,l$y_w,lambda[k])
    }
    IF_x <- IF_x |> mutate(u = ooo2$IF_x[order(orx)])
    IF_y <- IF_y |> mutate(u = ooo2$IF_y[order(ory)])
    theta <- theta |> mutate(u = ooo2$theta)

    ## NET BENEFIT
    #ooo3 <- c_influence_netbenefit(l$x[orx],l$y[ory],l$x_uni,l$y_uni,l$x_w,l$y_w,lambda[k])
    IF_x <- IF_x |> mutate(n = f-u)
    IF_y <- IF_y |> mutate(n = f-u)
    theta <- theta |> mutate(n = f-u)


    ## WIN RATIO
    #ooo4 <- c_influence_winratio(l$x[orx],l$y[ory],l$x_uni,l$y_uni,l$x_w,l$y_w,lambda[k])
    IF_x <- IF_x |> mutate(w = f/theta$f-u/theta$u)
    IF_y <- IF_y |> mutate(w = f/theta$f-u/theta$u)
    theta <- theta |> mutate(w = log(f)-log(u) )

    IF_x <- IF_x |> mutate(Variable=xxx)
    IF_y <- IF_y |> mutate(Variable=xxx)
    theta <- theta |> mutate(Variable=xxx)
    list(theta =theta ,IF_x =IF_x ,IF_y =IF_y )
  })

  ttt <- lapply(temp,function(vvv){
    vvv$theta
  })
  theta <- do.call("rbind",ttt)

  ttt <- lapply(temp,function(vvv){
    vvv$IF_x
  })
  IF_x <- do.call("rbind",ttt)

  ttt <- lapply(temp,function(vvv){
    vvv$IF_y
  })
  IF_y <- do.call("rbind",ttt)

  var_types <- sapply(fit$Variables, function(v) v$type)

  structure(
    list(theta =theta ,IF_x =IF_x ,IF_y =IF_y),
    class = "harvest",
    var_types = var_types
  )

}
