# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Subject-Level Influence Functions for Favorable Outcome Estimand
#'
#' @description
#' Computes subject-level influence function (IF) values for the favorable outcome
#' estimand \eqn{A = P(X \ge Y + \lambda)} under right-censoring. The function handles
#' missing data (\code{NA} values) safely and maps computed influence values back
#' to the original row ordering of the input dataset.
#'
#' @param arm A \code{CharacterVector} specifying treatment allocation (\code{"X"} or \code{"Y"}).
#' @param time A \code{NumericVector} of observed event or censoring times.
#' @param status An \code{IntegerVector} of event status indicators (\code{1} for event, \code{0} for censored).
#' @param lambda_val A \code{double} specifying the margin/threshold shift (\eqn{\lambda}) applied to arm Y outcomes.
#'
#' @details
#' The influence function calculations account for Kaplan-Meier/ECDF estimation under right-censoring:
#' \enumerate{
#'   \item \bold{NA Handling & Indexing:} Identifies complete cases per arm (\code{idx_X}, \code{idx_Y}) while preserving original row positions. Returns an \code{NA}-filled column if either group lacks valid data.
#'   \item \bold{Cross-Arm Survival Prediction:} Evaluates step-function survival probabilities \eqn{S_X(Y + \lambda)} and \eqn{S_Y(X - \lambda)} using \code{\link{c_ecdf_predict_less}}.
#'   \item \bold{Arm X Influence Calculation (\eqn{\text{IF}_X}):} Evaluates the martingale-based influence components accounting for the probability at risk \eqn{H_X(t)} and cumulative hazard increments \eqn{d\Lambda_X(t)}.
#'   \item \bold{Arm Y Influence Calculation (\eqn{\text{IF}_Y}):} Computes corresponding martingale integral terms for control group observations.
#'   \item \bold{Row Reconstruction:} Re-aligns computed \eqn{\text{IF}_X} and \eqn{\text{IF}_Y} values into an \eqn{N}-length vector, placing \code{NA_REAL} in rows where inputs were incomplete.
#' }
#'
#' @return A \code{DataFrame} containing four columns matching the original length \eqn{N}:
#' \item{arm}{Original \code{arm} vector.}
#' \item{time}{Original \code{time} vector.}
#' \item{status}{Original \code{status} vector.}
#' \item{IF}{Computed subject-level influence function value (or \code{NA} for incomplete cases).}
#'
#' @name c_IF_fav_censoring
#' @export
c_IF_fav_censoring <- function(arm, time, status, lambda_val) {
    .Call(`_infuse_c_IF_fav_censoring`, arm, time, status, lambda_val)
}

#' Calculate Uncensored Subject-Level Influence Functions for Favorable Outcome Estimand
#'
#' @description
#' Computes subject-level influence function (IF) values for the favorable outcome
#' estimand \eqn{A = P(X \ge Y + \lambda)} when outcomes are fully observed (uncensored).
#' Automatically handles \code{NA} values and restores computed influence values back to
#' the original row order of the input vectors.
#'
#' @param arm A \code{CharacterVector} specifying treatment allocation (\code{"X"} or \code{"Y"}).
#' @param time A \code{NumericVector} of fully observed outcomes/times (no status variable required).
#' @param lambda_val A \code{double} specifying the margin/threshold shift (\eqn{\lambda}) applied to arm Y outcomes.
#'
#' @details
#' In the absence of censoring, the empirical influence functions simplify to direct ECDF projections:
#' \enumerate{
#'   \item \bold{NA-Safe Filtering:} Identifies valid cases for arm X (\code{idx_X}) and arm Y (\code{idx_Y}). If either group has no complete cases, returns an \code{NA}-filled output table.
#'   \item \bold{Empirical CDF Estimation:} Fits unweighted ECDFs using \code{\link{c_ecdf_plus}} without status indicators.
#'   \item \bold{Cross-Arm Predictions:} Computes \eqn{S_X(Y_j + \lambda) = 1 - F_X(Y_j + \lambda)} for arm Y subjects and \eqn{F_Y(X_i - \lambda)} for arm X subjects using \code{\link{c_ecdf_predict_less}}.
#'   \item \bold{Point Estimate (\eqn{A}):} Calculates \eqn{A = \frac{1}{n_Y} \sum_{j=1}^{n_Y} S_X(Y_j + \lambda)}.
#'   \item \bold{Exact IF Evaluation:}
#'     \itemize{
#'       \item \bold{Arm X subjects:} \eqn{\text{IF}_{X, i} = F_Y(X_i - \lambda) - A}
#'       \item \bold{Arm Y subjects:} \eqn{\text{IF}_{Y, j} = S_X(Y_j + \lambda) - A}
#'     }
#'   \item \bold{Row Realignment:} Places calculated \eqn{\text{IF}} values into an \eqn{N}-length vector, setting missing/incomplete rows to \code{NA_REAL}.
#' }
#'
#' @return A \code{DataFrame} containing three columns matching the original length \eqn{N}:
#' \item{arm}{Original \code{arm} vector.}
#' \item{time}{Original \code{time} vector.}
#' \item{IF}{Computed subject-level influence function value (or \code{NA} for incomplete cases).}
#'
#' @name c_IF_fav_no_censoring
#' @export
c_IF_fav_no_censoring <- function(arm, time, lambda_val) {
    .Call(`_infuse_c_IF_fav_no_censoring`, arm, time, lambda_val)
}

#' Flexible Empirical Cumulative Distribution Function (Unified CDF)
#'
#' @description A high-performance unified function to calculate the Empirical
#' Cumulative Distribution Function (ECDF) for any numerical variable. It
#' automatically generalizes to the Kaplan-Meier estimator when right-censoring
#' indicators are provided, making it suitable for both general statistics
#' and time-to-event analysis.
#'
#' @param x A numeric vector of observations (e.g., ages, heights, or survival times). NAs are ignored in calculations but preserved in output.
#' @param xs An optional integer vector of indicators. For survival data:
#' (1 = event, 0 = censored). For standard ECDF: leave NULL or provide all 1s.
#'
#' @return A named \code{List} containing:
#' \itemize{
#'   \item \code{p}: The cumulative probabilities \eqn{F(x)}. In the absence of
#'   censoring, this matches the standard ECDF.
#'   \item \code{w}: The probability mass or "weight" assigned to each observation.
#'   \item \code{o}: The 1-based ordering index used during the internal calculation.
#'   \item \code{pi}: Numeric vector mapping the proportion of the non-NA cohort
#'         remaining at risk (\eqn{\hat{\pi}(t)}) at that individual's time point.
#'   \item \code{lambda_jump}: Numeric vector containing the hazard jump (\eqn{d\hat{\Lambda}(t)}),
#'         equivalent to the status indicator divided by the current size of the risk set.
#' }
#'
#' @details
#' When \code{xs} is NULL, this function computes the standard ECDF by assigning
#' equal weights (\eqn{1/n}) to all observations. When \code{xs} is provided,
#' it applies the "Redistribute-to-the-Right" algorithm.
#'
#' To ensure consistency with survival analysis theory, ties in \code{x} are
#' resolved by placing events before censoring. The output is always mapped
#' back to the original input order of \code{x}.
#'
#' @examples
#'
#' x <- c(1, 2, 2, 3, 5)
#' c_ecdf_plus(x)
#'
#' # Example with more data
#' set.seed(123)
#' y <- rnorm(100)
#' res_y <- c_ecdf_plus(y)
#' or <- res_y$o
#' plot(y[or], res_y$p[or], type = "s", main = "C++ ECDF")
#'
#'
#' data_points <- c(5, 1, 3, 1, 5, 5)
#' result <- c_ecdf_plus(data_points)
#'
#' # Access cumulative weights
#' print(result$p[result$o])
#'
#' # compare to ecdf
#' x <- c(1,2,4,2,2,35,6,3,2,3,1,3)
#' c_ecdf_plus(x)
#' unique(x)
#' ecdf(x)(unique(x))
#'
#'
#' times <- c(10, 20, 20, 30)
#' status <- c(1, 0, 1, 1) # Note the tie at 20
#'
#' # Calculate KM stats
#' res <- c_ecdf_plus(times, status)
#'
#' # The weights for censored items will be 0
#' res$w
#'
#' # Example data: times and event status
#' times <- c(10, 20, 20, 35, 40, 50)
#' status <- c(1, 1, 0, 1, 0, 1)
#'
#' km_res <- c_ecdf_plus(times, status)
#'
#' # Plotting the cumulative incidence step function
#' plot(times, km_res$p[km_res$o], type = "s",
#'      xlab = "Time", ylab = "Cumulative Incidence",
#'      main = "KM Estimate")
#'
#'
#' # Test with ipilimumab data
#' data(ipilimumab)
#' dat <- ipilimumab
#' res_ipili <- c_ecdf_plus(dat$time, dat$event)
#' fit_ipili <- survfit(Surv(time, event) ~ 1, data = dat)
#'
#' # Check equivalence
#' plot(summary(fit_ipili)$time,1-summary(fit_ipili)$surv,type="s")
#'  or <- res_ipili$o
#' points(dat$time[or],res_ipili$p[or],col="red",type="s")
#'
#'
#'
#' @export
c_ecdf_plus <- function(x, xs = NULL) {
    .Call(`_infuse_c_ecdf_plus`, x, xs)
}

#' Predict Probabilities from ECDF or Kaplan-Meier Results
#'
#' @description Map new numeric values to cumulative probabilities using
#' the step function defined by previously calculated ECDF or Kaplan-Meier results.
#' This function implements a right-continuous mapping: \eqn{F(z) = P(X \le z)}.
#'
#' @param z A numeric vector of query values (points at which to evaluate the function).
#' @param x_sorted A numeric vector of observed values, sorted in non-decreasing order.
#' Usually obtained via \code{x[eee$o]} from \code{c_ecdf_plus}.
#' @param p_sorted A numeric vector of cumulative probabilities corresponding to \code{x_sorted}.
#' Usually obtained via \code{p[eee$o]} from \code{c_ecdf_plus}.
#'
#' @return A numeric vector of the same length as \code{z} containing the
#' mapped cumulative probabilities. Returns \code{0.0} for values smaller than
#' the minimum of \code{x_sorted} and the last calculated probability for
#' values larger than the maximum of \code{x_sorted}.
#'
#' @details
#' The function uses \code{std::upper_bound} (binary search) to achieve
#' \eqn{O(\log n)} lookup time per query point, making it highly efficient for
#' large datasets. It correctly handles \code{NA} values in the query vector \code{z}.
#'
#' @examples
#' # 1. Fit the model
#' x <- c(1, 2, 3, 4, 5)
#' eee <- c_ecdf_plus(x)
#'
#' # 2. Prepare sorted inputs for prediction
#' x_s <- x[eee$o]
#' p_s <- eee$p[eee$o]
#'
#' # 3. Predict for new values
#' z_new <- c(0.5, 2, 2.5, 10)
#' c_ecdf_predict(z_new, x_s, p_s)
#' # Expected: 0.0, 0.4, 0.4, 1.0
#'
#' times <- c(1, 3, 5)
#' probs <- c(0.2, 0.5, 0.9)
#' points <- c(0, 2, 4, 6)
#' # Map points to probabilities with an offset
#' c_ecdf_predict(points,times, probs)
#' # Returns: c(0, 0.2, 0.5, 0.9)
#'
#'
#' # Basic Usage
#' x <- c(4, 3, 2, 5, 34, 52, 64, 87, 23)
#' tf <- c_ecdf_plus(x)
#' x_s <- x[tf$o]
#' p_s <- tf$p[tf$o]
#' c_ecdf_predict(3,x_s, p_s)
#' c_ecdf_predict(2.99,x_s, p_s)
#'
#' # Comparison with base R ecdf
#' z <- c(2, 4, 23, 100)
#' base_r <- ecdf(x)(z)
#' custom_cpp <- c_ecdf_predict(z,x_s, p_s)
#' all.equal(base_r, custom_cpp)
#'
#'
#' @export
c_ecdf_predict <- function(z, x_sorted, p_sorted) {
    .Call(`_infuse_c_ecdf_predict`, z, x_sorted, p_sorted)
}

#' Predict Probabilities (Strictly Less Than)
#'
#' @description Map new numeric values to cumulative probabilities using
#' the step function defined by previously calculated ECDF or Kaplan-Meier results.
#' This function implements a left-continuous mapping: \eqn{F(z-) = P(X < z)}.
#'
#' @param z A numeric vector of query values.
#' @param x_sorted A numeric vector of observed values, sorted in non-decreasing order.
#' @param p_sorted A numeric vector of cumulative probabilities corresponding to \code{x_sorted}.
#'
#' @return A numeric vector representing \eqn{P(X < z)}.
#'
#' @examples
#'
#' # Basic Usage
#' x <- c(4, 3, 2, 5, 34, 52, 64, 87, 23)
#' tf <- c_ecdf_plus(x)
#' x_s <- x[tf$o]
#' p_s <- tf$p[tf$o]
#' c_ecdf_predict(3.01,x_s, p_s)
#' c_ecdf_predict(3,x_s, p_s)
#' c_ecdf_predict(2.99,x_s, p_s)
#'
#' c_ecdf_predict_less(3.01,x_s, p_s)
#' c_ecdf_predict_less(3,x_s, p_s)
#' c_ecdf_predict_less(2.99,x_s, p_s)
#'
#' @export
c_ecdf_predict_less <- function(z, x_sorted, p_sorted) {
    .Call(`_infuse_c_ecdf_predict_less`, z, x_sorted, p_sorted)
}

#' Extend the tail of a distribution using Generalized Pareto Distribution (GPD)
#'
#' @description This function takes existing observation vectors and extends
#' them by generating extra values based on GPD parameters. It combines the
#' original data with newly generated tail data.
#'
#' @param uni A NumericVector of existing observation values.
#' @param w A NumericVector of existing probabilities/weights.
#' @param mlesi Double; the scale parameter for the GPD.
#' @param mlesh Double; the shape parameter for the GPD.
#' @param extra_n Double; the number of extra points to generate for the tail.
#'
#' @return A named list containing:
#' \itemize{
#'   \item \code{uni}: A combined numeric vector of original and extended values.
#'   \item \code{w}: A combined numeric vector of associated probabilities/weights.
#' }
#'
#'
#' @examples
#' \dontrun{
#' library(data.table)
#' data(ipilimumab)
#' dat <- as.data.table(ipilimumab)
#'
#' #########################################################
#' # Example 1: Ipilimumab Arm Tail Extension
#' #########################################################
#'
#' # Read the data
#' X <- dat[arm == "ipilimumab", time]
#' Xs <- dat[arm == "ipilimumab", event]
#'
#' # Artificially censor the last few events to illustrate functionality
#' wher <- X > 26
#' Xs[wher] <- 0
#' X[wher] <- X[wher][1]
#'
#' # Estimate the ECDF using Kaplan-Meier logic
#' fit <- c_ecdf_plus(X, Xs)
#' or <- fit$o
#'
#' # Plot the initial ECDF
#' plot(X[or], fit$p[or], type = "s", ylim = c(0, 1),
#'      main = "GPD Tail Extension (Ipilimumab)")
#' abline(h = 1, lty = 3)
#'
#' # Estimate scale and shape parameters for the GPD
#' p <- param_gpd(X[or], Xs[or])
#'
#' # Extend the tail using GPD parameters
#' uni <- X[or]
#' w <- fit$p[or]
#' ta <- c_extendtail(uni, w, p$mlesi, p$mlesh, p$extra_n)
#'
#' # Visualize the extension in red
#' plot(w ~ uni, data = ta, type = "s", col = "red", ylim = c(0, 1),
#'      xlim = c(0, max(ta$uni)), xlab = "Time", ylab = "ECDF")
#' points(w ~ uni, type = "s")
#' abline(h = 1, lty = 3)
#'
#' #########################################################
#' # Example 2: Placebo Arm with Custom Extension Lengths
#' #########################################################
#'
#' # Read the data
#' X <- dat[arm == "placebo", time]
#' Xs <- dat[arm == "placebo", event]
#'
#' # Censor data after time 10
#' wher <- X > 10
#' Xs[wher] <- 0
#' X[wher] <- X[wher][1]
#'
#' # Estimate ECDF and GPD parameters
#' fit <- c_ecdf_plus(X, Xs)
#' or <- fit$o
#' p <- param_gpd(X[or], Xs[or])
#'
#' # Extend the tail with 10 simulated values
#' ta10 <- c_extendtail(X[or], fit$p[or], p$mlesi, p$mlesh, extra_n = 10)
#'
#' # Plot 10-value extension
#' plot(w ~ uni, data = ta10, type = "s", col = "red", ylim = c(0, 1),
#'      xlim = c(0, max(ta10$uni)), main = "Extension: 10 values")
#' points(X[or], fit$p[or], type = "s")
#' abline(h = 1, lty = 3)
#'
#' # Extend the tail with only 5 values
#' ta5 <- c_extendtail(X[or], fit$p[or], p$mlesi, p$mlesh, extra_n = 5)
#'
#' # Plot 5-value extension
#' plot(w ~ uni, data = ta5, type = "s", col = "blue", ylim = c(0, 1),
#'      xlim = c(0, max(ta5$uni)), main = "Extension: 5 values")
#' points(X[or], fit$p[or], type = "s")
#' abline(h = 1, lty = 3)
#' }
#' @export
c_extendtail <- function(uni, w, mlesi, mlesh, extra_n) {
    .Call(`_infuse_c_extendtail`, uni, w, mlesi, mlesh, extra_n)
}

#' Calculate Favorable Outcome Estimand A with Censoring and Margin Shift
#'
#' @description
#' Computes the population-level favorable outcome probability \eqn{A = P(X \ge Y + \lambda)}
#' between two treatment arms ("X" and "Y"). It handles continuous or time-to-event
#' data with optional right-censoring via non-parametric survival/ECDF estimation.
#'
#' @param arm A \code{CharacterVector} specifying group allocation (must contain \code{"X"} or \code{"Y"}).
#' @param time A \code{NumericVector} of observed event or censoring times.
#' @param status An \code{IntegerVector} indicating event status (typically \code{1} for observed event, \code{0} for censored).
#' @param lambda_val A \code{double} specifying a margin or threshold shift (\eqn{\lambda}) applied to arm Y's outcomes.
#'
#' @details
#' The function executes the following steps:
#' \enumerate{
#'   \item \bold{Complete Case Filtering:} Automatically filters out observations where \code{arm}, \code{time}, or \code{status} contains \code{NA}.
#'   \item \bold{Group-wise Non-parametric Estimation:} Fits Kaplan-Meier / modified ECDF step functions using \code{\link{c_ecdf_plus}} separately for arm X and arm Y.
#'   \item \bold{Predictive Evaluation:} Evaluates the survival probability \eqn{S_X(t) = P(X \ge t)} at shifted time points \eqn{t_Y + \lambda} via \code{\link{c_ecdf_predict_less}}.
#'   \item \bold{Weighted Integration:} Computes the overall estimand \eqn{A = \sum S_X(Y_j + \lambda) \cdot w_{Y, j}} using the survival jumps/weights (\eqn{w_Y}).
#' }
#'
#' @return A \code{double} representing the favorable outcome probability \eqn{A}.
#' Returns \code{NA_REAL} if either treatment group contains zero complete cases.
#'
#' @export
c_fav <- function(arm, time, status, lambda_val) {
    .Call(`_infuse_c_fav`, arm, time, status, lambda_val)
}

