# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Empirical Cumulative Distribution Function (ECDF)
#'
#' @description Calculates the jump points of the empirical cumulative 
#' distribution function. It identifies unique sorted values and their 
#' corresponding cumulative probabilities.
#'
#' @param x A numeric vector of observations.
#'
#' @return A named list containing two components:
#' \itemize{
#'   \item \code{uni}: A numeric vector of the unique sorted values of \code{x}.
#'   \item \code{w}: A numeric vector of the cumulative probabilities \eqn{P(X \le x)}.
#' }
#'
#' @details
#' The function sorts the input vector and identifies unique values. The 
#' probability for each unique value \eqn{x_j} is calculated as \eqn{F(x_j) = i/n}, 
#' where \eqn{i} is the count of all elements \eqn{\le x_j}. This is equivalent 
#' to the "knots" and "weights" of a standard ECDF.
#'
#' @examples
#' \dontrun{
#' x <- c(1, 2, 2, 3, 5)
#' res <- c_ecdf(x)
#' 
#' # Compare with base R ecdf()
#' fit_base <- ecdf(x)
#' 
#' # Check unique values (knots)
#' all.equal(res$uni, knots(fit_base))
#' 
#' # Check probabilities at those knots
#' all.equal(res$w, fit_base(knots(fit_base)))
#' 
#' # Example with more data
#' set.seed(123)
#' y <- rnorm(100)
#' res_y <- c_ecdf(y)
#' plot(res_y$uni, res_y$w, type = "s", main = "C++ ECDF")
#' }
#' 
#' data_points <- c(5, 1, 3, 1, 5, 5)
#' result <- c_ecdf(data_points)
#'
#' # Access unique values
#' print(result$uni)
#'
#' # Access cumulative weights
#' print(result$w)
#'
#' # compare to ecdf
#' x <- c(1,2,4,2,2,35,6,3,2,3,1,3)
#' c_ecdf(x)
#' unique(x)
#' ecdf(x)(unique(x))
#'
#' # CHECK SPEED
#' large_data <- rnorm(100000)
#' # Time the C++ Wrapper
#' start_time <- Sys.time()
#'
#'    res_cpp <- c_ecdf(large_data)
#'
#' end_time <- Sys.time()
#' t1 <- as.numeric(end_time - start_time)
#'
#' start_time <- Sys.time()
#'
#'    res_r <- ecdf(large_data)(unique(large_data))
#'
#' end_time <- Sys.time()
#' t2 <- as.numeric(end_time - start_time)
#' cat("\n Speed C++ ",t1,"\n Speed R ",t2,"\n Ratio",t2/t1,"\n")
#' @export
c_ecdf <- function(x) {
    .Call(`_infuse_c_ecdf`, x)
}

#' Kaplan-Meier Product-Limit Estimator (C++ Implementation)
#'
#' @description Computes the Kaplan-Meier estimate of the cumulative incidence 
#' (1 - S(t)) for right-censored data and returns a structured list. This 
#' implementation is optimized for speed and correctly handles tied event times.
#'
#' @param ttt A numeric vector of observed times (time-to-event or time-to-censoring).
#' @param sss An integer vector of status indicators (1 = event/death, 0 = censored).
#'
#' @return A named list containing two components:
#' \itemize{
#'   \item \code{uni}: A numeric vector of the unique event times (sorted).
#'   \item \code{w}: A numeric vector of the cumulative incidence (1 - S(t)) 
#'   calculated at those times.
#' }
#'
#' @details
#' The function calculates survival probability using the formula:
#' \deqn{\hat{S}(t) = \prod_{i: t_i \le t} \left(1 - \frac{d_i}{n_i}\right)}
#' where \eqn{d_i} is the number of events at time \eqn{t_i} and \eqn{n_i}
#' is the number of subjects at risk just before \eqn{t_i}.
#'
#' Note: If an observation is censored at the same time an event occurs, the
#' censored observation is assumed to remain at risk for that event (standard
#' Kaplan-Meier convention).
#'
#' @examples
#' \dontrun{
#' # Example data: times and event status
#' times <- c(10, 20, 20, 35, 40, 50)
#' status <- c(1, 1, 0, 1, 0, 1)
#'
#' km_res <- c_ecdf_surv(times, status)
#'
#' # Plotting the cumulative incidence step function
#' plot(km_res$uni, km_res$w, type = "s",
#'      xlab = "Time", ylab = "Cumulative Incidence",
#'      main = "KM Estimate")
#'
#' # Comparison with survival package
#' x <- c(0.2, 1, 2, 4, 2, 2, 35, 6, 3, 2, 3, 1, 3, 1.5, 45, 23, 12)
#' xs <- c(1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0)
#' 
#' library(survival)
#' fit <- survfit(Surv(x, xs) ~ 1)
#' fit1 <- c_ecdf_surv(x, xs)
#'
#' data.frame(time1 = summary(fit)$time,
#'            time2 = fit1$uni,
#'            surv1 = 1 - summary(fit)$surv,
#'            surv2 = fit1$w)
#'
#' # Test with ipilimumab data
#' data(ipilimumab)
#' dat <- ipilimumab
#' res_ipili <- c_ecdf_surv(dat$time, dat$event)
#' fit_ipili <- survfit(Surv(time, event) ~ 1, data = dat)
#' 
#' # Check equivalence
#' all.equal(res_ipili$uni, summary(fit_ipili)$time)
#' all.equal(res_ipili$w, 1 - summary(fit_ipili)$surv)
#'
#' # ++++++ TEST SPEED
#' start.time <- Sys.time()
#' fit_bench <- survfit(Surv(x, xs) ~ 1)
#' end.time <- Sys.time()
#' time.taken1 <- as.numeric(end.time - start.time)
#'
#' start.time <- Sys.time()
#' tf_bench <- c_ecdf_surv(x, xs)
#' end.time <- Sys.time()
#' time.taken2 <- as.numeric(end.time - start.time)
#'
#' time.taken1
#' time.taken2
#' time.taken1 / time.taken2
#' }
#'
#' @export
c_ecdf_surv <- function(ttt, sss) {
    .Call(`_infuse_c_ecdf_surv`, ttt, sss)
}

#' Map Values to Empirical Distribution Steps
#'
#' @description This function evaluates a step function (like an ECDF or Kaplan-Meier
#' estimate) at specific points. For each value in \code{z}, it finds the
#' corresponding value in \code{w} based on the intervals defined by \code{uni}.
#'
#' @param uni A sorted numeric vector of unique time points or breakpoints.
#' @param w A numeric vector of weights or probabilities associated with each
#' interval in \code{uni}. Must have the same length as \code{uni}.
#' @param z A numeric vector of points at which the function should be evaluated.
#' @param ofset A numeric value subtracted from each element of \code{z}
#' before evaluation. Defaults to 0.
#'
#' @return A numeric vector of the same length as \code{z} containing the
#' mapped values from \code{w}.
#'
#' @details
#' The function performs an "on-the-fly" lookup using a binary search
#' (\code{std::upper_bound}). For a given target \eqn{t = z_i - \text{ofset}},
#' the result is:
#' \itemize{
#'   \item 0 if \eqn{t < \text{uni}[0]}
#'   \item \eqn{w[j-1]} where \eqn{j} is the index such that \eqn{\text{uni}[j-1] \le t < \text{uni}[j]}
#' }
#' This is optimized to avoid temporary vector allocations and is much faster
#' than manual looping in R.
#'
#' @examples
#' \dontrun{
#' times <- c(1, 3, 5)
#' probs <- c(0.2, 0.5, 0.9)
#' points <- c(0, 2, 4, 6)
#' # Map points to probabilities with an offset
#' c_ecdf_values(times, probs, points, ofset = 0)
#' # Returns: c(0, 0.2, 0.5, 0.9)
#' }
#'
#' @export
c_ecdf_values <- function(uni, w, z, ofset = 0) {
    .Call(`_infuse_c_ecdf_values`, uni, w, z, ofset)
}

#' Map Values to Empirical Distribution Steps (Strictly Less Than)
#'
#' @description Evaluates a step function (like an ECDF) at specific points
#' using the logic \eqn{P(X < z)}. This results in a left-continuous
#' function, where the value at a jump point is the value of the lower step.
#'
#' @param uni A sorted numeric vector of unique time points or breakpoints.
#' @param w A numeric vector of weights or probabilities associated with
#' each interval.
#' @param z A numeric vector of points at which the function should be evaluated.
#' @param ofset A numeric value subtracted from each element of \code{z}.
#' Defaults to 0.
#'
#' @return A numeric vector of the same length as \code{z} containing the
#' mapped values from \code{w}.
#'
#' @details
#' This function uses \code{std::lower_bound} to find the first index where
#' \code{uni >= target}. Consequently, it maps to the weight associated with
#' values strictly less than the target.
#'
#' For a given target \eqn{t = z_i - \text{ofset}}, the result is:
#' \itemize{
#'   \item 0 if \eqn{t \le \text{uni}[0]}
#'   \item \eqn{w[j-1]} where \eqn{j} is the index such that \eqn{\text{uni}[j-1] < t \le \text{uni}[j]}
#' }
#'
#' @examples
#' \dontrun{
#' # Standard ECDF (X <= z) vs Strict ECDF (X < z)
#' times <- c(1, 3, 5)
#' weights <- c(0.2, 0.5, 0.9)
#'
#' # At the jump point (z = 3):
#' # c_ecdf_values would return 0.5
#' # c_ecdf_values_less returns 0.2
#' c_ecdf_values_less(times, weights, 3, ofset = 0)
#' }
#'
#' @export
c_ecdf_values_less <- function(uni, w, z, ofset = 0) {
    .Call(`_infuse_c_ecdf_values_less`, uni, w, z, ofset)
}

#' Extend the tail of a distribution using Generalized Pareto Distribution (GPD)
#' 
#' @description This function takes existing observation vectors and extends 
#' them by generating extra values based on GPD parameters. It combines the 
#' original data with newly generated tail data.
#' 
#' @param uni A NumericVector of existing observation values.
#' @param w A NumericVector of existing probabilities/weights.
#' @param mlesi Double; the scale parameter for the GPD.
#' @param mlesh Double; the shape parameter for the GPD.
#' @param extra_n Double; the number of extra points to generate for the tail.
#' 
#' @return A named list containing:
#' \itemize{
#'   \item \code{uni}: A combined numeric vector of original and extended values.
#'   \item \code{w}: A combined numeric vector of associated probabilities/weights.
#' }
#' 
#' 
#' @examples
#' \dontrun{
#' data(ipilimumab)
#' dat <- ipilimumab
#' 
#' ### Read the data
#' X <- dat %>% filter(arm=="ipilimumab") %>% pull(time)
#' Xs <- dat %>% filter(arm=="ipilimumab") %>% pull(event)
#' 
#' ### Remove the last few events to illustrate the functionality
#' wher <- X>26
#' Xs[wher] <- 0
#' 
#' ### Estimate and plot the Kaplan-Meier estimation of the ECDF
#' fit <- c_ecdf_surv(X,Xs)
#' plot(w~uni,data=fit,type="s",ylim=c(0,1))
#' abline(h=1,lty=3)
#' 
#' ### Estimate the scale and shape parameters for the GPD
#' p <- param_gpd(X,Xs)
#' 
#' ### Extend the tail
#' uni <- fit$uni
#' w <- fit$w
#' mlesi <- p$mlesi
#' mlesh <- p$mlesh
#' ta <- c_extendtail(uni,w,mlesi,mlesh,p$extra_n)
#' ta
#' 
#' ### plot the extension
#' plot(w~uni,data=ta,type="s",col="red",ylim=c(0,1),xlim = c(0,max(ta$uni)))
#' points(w~uni,data=fit,type="s")
#' abline(h=1,lty=3)
#'
#' ###############
#' ### Example 2
#' ###############
#' ### Read the data
#' X <- dat %>% filter(arm=="placebo") %>% pull(time)
#' Xs <- dat %>% filter(arm=="placebo") %>% pull(event)
#' 
#' ### Remove the last few events to illustrate the functionality
#' wher <- X>10
#' Xs[wher] <- 0
#' 
#' ### Estimate aplan-Meier estimation of the ECDF
#' fit <- c_ecdf_surv(X,Xs)
#' 
#' ### Estimate the scale and shape parameters for the GPD
#' p <- param_gpd(X,Xs)
#' 
#' ### Extend the tail
#' ta <- c_extendtail(fit$uni,fit$w,p$mlesi,p$mlesh,extra_n=10)
#' ta
#' 
#' ### plot the extension
#' plot(w~uni,data=ta,type="s",col="red",ylim=c(0,1),xlim = c(0,max(ta$uni)))
#' points(w~uni,data=fit,type="s")
#' abline(h=1,lty=3)
#' 
#' ### Extend the tail but only with 5 values
#' ta <- c_extendtail(fit$uni,fit$w,p$mlesi,p$mlesh,extra_n=5)
#' ta
#' 
#' ### plot the extension
#' plot(w~uni,data=ta,type="s",col="red",ylim=c(0,1),xlim = c(0,max(ta$uni)))
#' points(w~uni,data=fit,type="s")
#' abline(h=1,lty=3)
#' }
#' @export
c_extendtail <- function(uni, w, mlesi, mlesh, extra_n) {
    .Call(`_infuse_c_extendtail`, uni, w, mlesi, mlesh, extra_n)
}

#' Find Interval Indices (C++ Implementation)
#'
#' @description For each element in x, this function finds the index of the
#' interval in breaks that contains the value. It uses a binary search
#' algorithm (\code{std::upper_bound}) for high performance.
#'
#' @param x A numeric vector of values to be localized.
#' @param breaks A numeric vector of sorted breakpoints defining the intervals.
#'
#' @return An integer vector of the same length as \code{x}. Each value
#' represents the number of breakpoints that are less than or equal to the
#' corresponding value in \code{x}.
#'
#' @details
#' The function mimics the behavior of \code{findInterval(x, breaks)} in
#' base R. Specifically:
#' \itemize{
#'   \item If \code{x[i] < breaks[1]}, it returns 0.
#'   \item If \code{breaks[j] <= x[i] < breaks[j+1]}, it returns j.
#'   \item If \code{x[i] >= breaks[last]}, it returns the length of breaks.
#' }
#'
#' Because it uses \code{std::upper_bound}, the complexity is \eqn{O(N \cdot \log M)},
#' where \eqn{N} is the length of \code{x} and \eqn{M} is the length of \code{breaks}.
#'
#' @examples
#' \dontrun{
#' x <- c(0, 5, 12, 25)
#' breaks <- c(1, 10, 20)
#' # Returns: c(0, 1, 1, 3)
#' winDwinR::c_findInterval(x, breaks)
#'
#' findInterval(x, breaks)
#' }
#'
#' # CHECK SPEED
#' x <- rnorm(1000)
#' breaks <- rnorm(100)
#' # Time the C++ Wrapper
#' start_time <- Sys.time()
#'
#'    res_cpp <- winDwinR::c_findInterval(x,breaks)
#'
#' end_time <- Sys.time()
#' t1 <- as.numeric(end_time - start_time)
#'
#' start_time <- Sys.time()
#'
#'    res_r <- findInterval(x,sort(breaks) )
#'
#' end_time <- Sys.time()
#' t2 <- as.numeric(end_time - start_time)
#' cat("\n Speed C++ ",t1,"\n Speed R ",t2,"\n Ratio",t2/t1,"\n")
#'
#' @export
#'
c_findInterval <- function(x, breaks) {
    .Call(`_infuse_c_findInterval`, x, breaks)
}

#' Calculate Win Probability Point Estimate and Influence Functions
#'
#' This function computes the point estimate for the probability of a favorable
#' pair (Win Probability, \code{P(X >= Y + lambda)}) and returns the influence functions
#' for both the treatment (X) and control (Y) groups. These influence functions
#' can be used for variance estimation and combining multiple outcomes.
#'
#' @param x NumericVector: Raw values of the treatment group.
#' @param y NumericVector: Raw values of the control group.
#' @param x_uni NumericVector: Sorted unique values of the treatment group (X).
#' @param y_uni NumericVector: Sorted unique values of the control group (Y).
#' @param x_w NumericVector: Cumulative ECDF weights for x_uni.
#' @param y_w NumericVector: Cumulative ECDF weights for y_uni.
#' @param lambda double: The clinically meaningful threshold for defining a win.
#'
#' @return List: A list containing:
#'    \item{theta}{Point Estimate: \code{P(X >= Y + lambda)}}
#'    \item{IF_x}{Influence Function values for the treatment group}
#'    \item{IF_y}{Influence Function values for the control group}
#'
#' @details
#' The win probability theta is calculated by integrating the ECDF of Y against
#' the empirical distribution of X. The influence functions are calculated as:
#' \code{IF_x = F_Y(x - lambda) - theta} and \code{IF_y = [1 - F_X_less(y + lambda)] - theta}.
#'
#' @export
c_influence_favorable <- function(x, y, x_uni, y_uni, x_w, y_w, lambda) {
    .Call(`_infuse_c_influence_favorable`, x, y, x_uni, y_uni, x_w, y_w, lambda)
}

#' Calculate Influence Functions for Net Benefit (Win Difference)
#'
#' @description
#' This function computes the point estimate for the Net Benefit (Win Difference)
#' and returns the individual-level influence functions for groups X and Y.
#' These components are used to derive standard errors and confidence intervals
#' for hierarchical or weighted outcomes.
#'
#' @param x NumericVector: Raw values for the first group (X).
#' @param y NumericVector: Raw values for the second group (Y).
#' @param x_uni NumericVector: Unique sorted values of group X.
#' @param y_uni NumericVector: Unique sorted values of group Y.
#' @param x_w NumericVector: Cumulative ECDF weights for unique X values.
#' @param y_w NumericVector: Cumulative ECDF weights for unique Y values.
#' @param lambda double: The margin of clinical significance.
#'
#' @return List: A named list containing:
#' \itemize{
#'    \item \code{theta}: The point estimate for Net Benefit \eqn{\theta = P(X > Y + \lambda) - P(Y > X + \lambda)}.
#'    \item \code{IF_x}: Numeric vector of influence functions for subjects in group X.
#'    \item \code{IF_y}: Numeric vector of influence functions for subjects in group Y.
#' }
#'
#' @details
#' The influence function for group X is defined as \eqn{IF_x(x) = h_1(x) - \theta},
#' and for group Y as \eqn{IF_y(y) = h_2(y) - \theta}.
#' The point estimate is calculated by integrating the weighted ECDFs using
#' the masses derived from \code{x_w} and \code{y_w}.
#'
#' @export
c_influence_netbenefit <- function(x, y, x_uni, y_uni, x_w, y_w, lambda) {
    .Call(`_infuse_c_influence_netbenefit`, x, y, x_uni, y_uni, x_w, y_w, lambda)
}

#' Calculate Loss Probability Point Estimate and Influence Functions
#'
#' This function computes the point estimate for the probability of an unfavorable
#' pair (Loss Probability, P(Y >= X + lambda)) and returns the influence functions
#' for both the treatment (X) and control (Y) groups.
#'
#' @param x NumericVector: Raw values of the treatment group.
#' @param y NumericVector: Raw values of the control group.
#' @param x_uni NumericVector: Sorted unique values of the treatment group (X).
#' @param y_uni NumericVector: Sorted unique values of the control group (Y).
#' @param x_w NumericVector: Cumulative ECDF weights for x_uni.
#' @param y_w NumericVector: Cumulative ECDF weights for y_uni.
#' @param lambda double: The clinically meaningful threshold for defining a loss.
#'
#' @return List: A list containing:
#'    \item{theta}{Point Estimate: P(Y >= X + lambda)}
#'    \item{IF_x}{Influence Function values for the treatment group}
#'    \item{IF_y}{Influence Function values for the control group}
#'
#' @details
#' The loss probability theta is calculated by integrating the ECDF of X evaluated
#' at (Y - lambda). The influence functions represent the centered contribution
#' of each observation to this probability.
#'
#' @export
c_influence_unfavorable <- function(x, y, x_uni, y_uni, x_w, y_w, lambda) {
    .Call(`_infuse_c_influence_unfavorable`, x, y, x_uni, y_uni, x_w, y_w, lambda)
}

#' Calculate Influence Functions for Win Ratio
#'
#' @description
#' This function computes the point estimate for the Win Ratio and returns
#' the individual-level influence functions for groups X and Y. These
#' components are calculated on the log-scale to maintain numerical symmetry
#' for standard error derivation.
#'
#' @param x NumericVector: Raw values for the first group (X).
#' @param y NumericVector: Raw values for the second group (Y).
#' @param x_uni NumericVector: Unique sorted values of group X.
#' @param y_uni NumericVector: Unique sorted values of group Y.
#' @param x_w NumericVector: Cumulative ECDF weights for unique X values.
#' @param y_w NumericVector: Cumulative ECDF weights for unique Y values.
#' @param lambda double: The margin of clinical significance.
#'
#' @return List: A named list containing:
#' \itemize{
#'    \item \code{theta}: The point estimate for the Log Win Ratio \eqn{\theta = \log(A) - \log(B)}.
#'    \item \code{IF_x}: Numeric vector of influence functions for group X (log-scale).
#'    \item \code{IF_y}: Numeric vector of influence functions for group Y (log-scale).
#' }
#'
#' @export
#'
c_influence_winratio <- function(x, y, x_uni, y_uni, x_w, y_w, lambda) {
    .Call(`_infuse_c_influence_winratio`, x, y, x_uni, y_uni, x_w, y_w, lambda)
}

#' Calculate the Weighted Mean Survival Time
#' 
#' @description A C++ implementation that calculates the mean by mapping 
#' sorted observations to their Kaplan-Meier cumulative incidence weights.
#' 
#' @param x A numeric vector of observed times.
#' @param xs An integer vector of status indicators (1 = event, 0 = censored).
#' 
#' @return A double representing the estimated mean.
#' 
#' @examples
#' \dontrun{
#' x <- c(0.2, 1, 2, 4, 2, 2, 35, 6, 3, 2, 3, 1, 3, 1.5, 45, 23, 12)
#' xs <- c(1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0)
#' c_mean(x, xs)
#' 
#' x <- rnorm(1000,40,2)
#' xs <- rbinom(1000,size=1,prob=0.6)
#' c_mean(x, xs)
#' 
#' x <- rnorm(1000,40,2)
#' xs <- rep(1,1000)
#' c_mean(x, xs)
#' mean(x)
#' }
#' 
#' @export
c_mean <- function(x, xs) {
    .Call(`_infuse_c_mean`, x, xs)
}

#' Optimized Order Function
#'
#' @description This function mimics the behavior of R's \code{order()} function
#' using C++'s \code{std::stable_sort}. It returns the 1-based indices that
#' would result in a sorted version of the input vector.
#'
#' @param x A numeric vector to be ordered.
#'
#' @return An integer vector of 1-based indices (matching R's indexing convention).
#'
#' @details
#' The function uses \code{std::stable_sort} to ensure that the relative
#' order of elements with equal values is preserved, making it perfectly
#' compatible with the default behavior of R's \code{order(..., method = "shell")}.
#'
#' @examples
#' # Create a vector with ties
#' x <- c(3, 2, 4, 3, 2, 1, 4)
#'
#' # Get indices from C++
#' cpp_idx <- winDwinR::c_order(x)
#'
#' # Get indices from base R
#' r_idx <- order(x)
#'
#' # Compare results
#' identical(cpp_idx, r_idx)
#'
#' # Use indices to sort the original vector
#' x[cpp_idx]
#'
#'
#' # CHECK SPEED
#' large_data <- rnorm(1000)
#' # Time the C++ Wrapper
#' start_time <- Sys.time()
#'
#'    res_cpp <- winDwinR::c_order(large_data)
#'
#' end_time <- Sys.time()
#' t1 <- as.numeric(end_time - start_time)
#'
#' start_time <- Sys.time()
#'
#'    res_r <- order(large_data)
#'
#' end_time <- Sys.time()
#' t2 <- as.numeric(end_time - start_time)
#' cat("\n Speed C++ ",t1,"\n Speed R ",t2,"\n Ratio",t2/t1,"\n")
#'
#' @export
#'
c_order <- function(x) {
    .Call(`_infuse_c_order`, x)
}

