#' Realise Statistical Inference from Infused Data
#'
#' @description
#' Calculates point estimates, standard errors, confidence intervals, and p-values
#' for Win/Loss statistics using Influence Functions. It supports both
#' individual outcome analysis and a weighted Non-Prioritized Outcome (NPO) summary.
#' It utilizes \code{data.table} for fast, in-place variance and covariance calculations.
#'
#' @param s An object of class \code{"infuse"} generated by the \code{infuse} function.
#' @param conf_level Numeric. The confidence level for intervals (default 0.95).
#' @param w Numeric vector. Optional weights for calculating the Non-Prioritized
#'    Outcome (NPO). Defaults to equal weighting.
#'
#' @return A tidy \code{data.table} of class \code{"realise"} summarizing each
#'    outcome and the NPO with:
#' \itemize{
#'    \item \code{Variable}: The outcome name (or "NPO").
#'    \item \code{Metric}: Favorable, Unfavorable, Net Treatment Benefit, Win Ratio, or GNNT.
#'    \item \code{Estimate}: The point estimate.
#'    \item \code{Se}: Standard error derived from Influence Functions.
#'    \item \code{Lower, Upper}: Wald-based or Wilson-adjusted confidence intervals.
#'    \item \code{PValue}: Two-sided p-value against the null hypothesis (NA for proportions).
#' }
#'
#' @details
#' The inference for the \bold{Win Ratio} is performed on the log-scale and
#' then back-transformed. The \bold{GNNT} (Generalized Number Needed to Treat)
#' is calculated as the ceiling of \eqn{1 / Net Benefit}. For small sample sizes
#' in Favorable/Unfavorable proportions (specifically when \eqn{n \times p < 10}),
#' a Wilson-adjusted interval is automatically applied for better coverage.
#'
#' @examples
#' # ---------------------------------------------------------
#' # Example 1: Survival Data
#' # ---------------------------------------------------------
#' data(ipilimumab)
#' s <- infuse(Surv(time, event)(6, high) ~ arm,
#'             data = ipilimumab,
#'             treated = "ipilimumab")
#'
#' h <- realise(s)
#' print(h)
#'
#' # ---------------------------------------------------------
#' # Example 2: Multiple Outcomes (NPO)
#' # ---------------------------------------------------------
#' data(obstetrics)
#' s <- infuse(PretermYN("Yes") + Birthweight(500, high) ~ Group,
#'             data = obstetrics,
#'             treated = "T")
#'
#' # Realise with equal weights (default)
#' h <- realise(s)
#'
#' # Realise with custom weights (e.g., more weight on PretermYN)
#' h_weighted <- realise(s, w = c(0.7, 0.3))
#'
#' # ---------------------------------------------------------
#' # Example 3: Continuous Data (Obstetrics)
#' # ---------------------------------------------------------
#' data(obstetrics)
#' # High birthweight is "good", 500g margin
#' s <- infuse(Birthweight(500, high) ~ Group,
#'                  data = obstetrics,
#'                  treated = "T")
#'
#' h <- realise(s)
#' print(h)
#'
#' # ---------------------------------------------------------
#' # Example 4: Longitudinal Binary Data (Respiratory)
#' # ---------------------------------------------------------
#' data(respiratory)
#' # We analyze status at the final visit (Visit 4)
#' resp_v4 <- respiratory[respiratory$visit == 4, ]
#' s <- infuse(outcome("Yes") ~ treat,
#'                  data = resp_v4,
#'                  treated = "A")
#'
#' h <- realise(s)
#' print(h)
#'
#' @import data.table
#' @importFrom stats qnorm pnorm
#' @export
realise <- function(s, conf_level = 0.95,w = NULL) {

  if (!inherits(s, "infuse")) stop("Input must be a 'infuse' object.")

  # --- 2. Setup Data ---
  n_vars    <- length(s$metadata$name)
  zz        <- qnorm(1 - (1 - conf_level) / 2)
  responses <- s$metadata$name

  PE <- s$metadata[,.(name,type,f,u)]
  setnames(PE,c("f","u"),c("A","B"))
  IF <- s$data[,.(p_i_d,arm,name,weight,f,u)]
  setnames(IF,c("f","u"),c("IF_A","IF_B"))
  IFm <- merge(IF,PE, by = "name", all.x = TRUE)

  # --- 3. Individual Outcomes ---
  indiv_df <- IFm[,`:=`(f_pe=A,f_ifval = IF_A,
                        u_pe = B, u_ifval = IF_B,
                        n_pe = A - B, n_ifval = IF_A - IF_B,
                        lw_pe = log(A) - log(B), lw_ifval = IF_A/A - IF_B/B)]
  indiv_df <- indiv_df[,.(name,arm,weight,f_pe,f_ifval,u_pe,u_ifval,n_pe,n_ifval,lw_pe,lw_ifval)]


  ## reshape in long format:
  long_df <- melt(
    indiv_df,
    measure.vars = measure(prefix, value.name, pattern = "^(.*)_(pe|ifval)$")
  )


  ## Calculate variances:
  result <- long_df[, .(S2 = sum(weight^2 * ifval^2, na.rm = TRUE)), by = .(name, arm, prefix,pe)]

  ## Calculate standard errors
  wide_result <- dcast(result, name + prefix + pe ~ arm, value.var = "S2")
  wide_result <- wide_result[, se := sqrt(X + Y)]

  # Calculate Wald stats
  ooo <- wide_result[, `:=`(LB = pe-zz*se, UB = pe+zz*se,PV = 2 * (1 - pnorm(abs(pe/se))))]
  setnames(ooo,c("prefix","name","pe","se"),c("Metric","Variable","E","SE"))
  ooo <- ooo[,.(Variable,Metric,E,SE,LB,UB,PV)]



  # --- 4. Non-Prioritized Outcome (NPO) ---
  if (n_vars > 1) {
    ww_vec <- if (is.null(w)) rep(1 / n_vars, n_vars) else w
    wdat   <- data.frame(name = responses, ww = ww_vec)
    IFm_w <- merge(IFm, wdat, by = "name", all.x = TRUE)

    IFm_w <- IFm_w[, .(
      IF_A = sum(weight * IF_A * ww, na.rm = TRUE) / sum(ww, na.rm = TRUE),
      IF_B = sum(weight * IF_B * ww, na.rm = TRUE) / sum(ww, na.rm = TRUE),
      A    = sum(A * ww, na.rm = TRUE) / sum(ww, na.rm = TRUE),
      B    = sum(B * ww, na.rm = TRUE) / sum(ww, na.rm = TRUE)
    ), by = .(p_i_d, arm)]

    # --- 3. Individual Outcomes ---
    idf <- IFm_w[,`:=`(f_pe=A,f_ifval = IF_A,
                       u_pe = B, u_ifval = IF_B,
                       n_pe = A - B, n_ifval = IF_A - IF_B,
                       lw_pe = log(A) - log(B), lw_ifval = IF_A/A - IF_B/B)]
    idf <- idf[,.(arm,f_pe,f_ifval,u_pe,u_ifval,n_pe,n_ifval,lw_pe,lw_ifval)]

    ## reshape in long format:
    ldf <- melt(
      idf,
      measure.vars = measure(prefix, value.name, pattern = "^(.*)_(pe|ifval)$")
    )

    ## Calculate variances:
    r <- ldf[, .(S2 = sum(ifval^2, na.rm = TRUE)), by = .(arm, prefix,pe)]

    ## Calculate standard errors
    wr <- dcast(r, prefix + pe ~ arm, value.var = "S2")
    wr <- wr[, se := sqrt(X + Y)]

    # Calculate Wald stats
    ooo1 <- wr[, `:=`(LB = pe-zz*se, UB = pe+zz*se,PV = 2 * (1 - pnorm(abs(pe/se))))]
    setnames(ooo1,c("prefix","pe","se"),c("Metric","E","SE"))
    ooo1$Variable <- "NPO"
    ooo1 <- ooo1[,.(Variable,Metric,E,SE,LB,UB,PV)]
    ooo <- rbind(ooo,ooo1)
    responses <- c(responses,"NPO")
  }


  # --- 5. Post-Processing & Transformations ---
  # 1. Back-transform Win Ratio
  # We subset to only the "lw" rows, and apply exp() to E, LB, and UB
  cols_to_exp <- c("E", "LB", "UB")
  ooo[Metric == "lw", (cols_to_exp) := lapply(.SD, exp), .SDcols = cols_to_exp]

  # 2. GNNT Logic
  # Create the new rows from the "n" metric
  new_rows <- ooo[Metric == "n"]

  # Mutate the new rows
  new_rows[, `:=`(
    Metric = "t",
    LB = ceiling(1 / (E + zz * SE)),
    UB = ceiling(1 / (E - zz * SE)),
    E  = ceiling(1 / E)
  )]

  # Bind the new rows back to the original dataset
  ooo <- rbind(ooo, new_rows)



  # Wilson Adjustment for small proportions
  ss <- s$metadata[, .(Variable = name, ssx, ssy)]

  # 2. Conditionally append the new row
  if (n_vars > 1) {
    ss <- rbind(ss,
      # Calculate minimums internally and bind instantly
      ss[, .(Variable = "NPO",
             ssx = min(ssx, na.rm = TRUE),
             ssy = min(ssy, na.rm = TRUE))])
  }
  ss <- ss[,nx := ssx+ssy]
  ooo2 <- merge(ooo, ss, by = "Variable", all.x = TRUE)

  # 1. Define the indices (conditions) to avoid recalculating them
  idx_prop <- ooo2[, Metric %in% c("f", "u")]
  idx_wilson <- ooo2[, idx_prop & ((nx * E < 10) | (nx * (1 - E) < 10))]

  # 2. Update LB and UB ONLY where the Wilson condition is true
  ooo2[idx_wilson, `:=`(
    LB = (1/(1+zz^2/nx)) * (E + zz^2/(2*nx) - zz * sqrt(SE^2 + zz^2/(4*nx^2))),
    UB = (1/(1+zz^2/nx)) * (E + zz^2/(2*nx) + zz * sqrt(SE^2 + zz^2/(4*nx^2)))
  )]

  # 3. Update PV to NA ONLY where the prop condition is true
  # Note: NA_real_ is the safer, stricter data.table equivalent to as.numeric(NA)
  ooo2[idx_prop, PV := NA_real_]
  ooo <- ooo2[,c("ssx","ssy","nx"):=NULL]

  # --- 6. Final Formatting ---
  # 1. Update/Create columns in-place
  final_df <- ooo[, .(
    Variable = factor(Variable, levels = responses),
    Metric   = factor(fcase(
      Metric == "f",  "Favorable",
      Metric == "u",  "Unfavorable",
      Metric == "n",  "Net Treatment Benefit",
      Metric == "lw", "Win Ratio",
      Metric == "t",  "GNNT"
    ), levels = c("Favorable", "Unfavorable", "Net Treatment Benefit", "Win Ratio", "GNNT")),
    Estimate = E,
    Se       = SE,
    Lower    = LB,
    Upper    = UB,
    PValue   = fifelse(PV < 0.001, "<0.001", as.character(round(PV, 3)))
  )]

  # 2. Arrange by Variable and Metric
  setorder(final_df, Variable, Metric)


  structure(final_df, class = c("realise","data.table", "data.frame"))

}
