#' Realise Statistical Inference from Infused Data
#'
#' @description
#' Calculates point estimates, standard errors, confidence intervals, and p-values
#' for Win/Loss statistics using pre-computed influence functions. It supports both
#' individual outcome analysis and a weighted Non-Prioritized Outcome (NPO) summary.
#' Leveraging \code{data.table}, it performs fast, in-place variance and covariance
#' calculations to construct asymptotic inference.
#'
#' @param s An object of class \code{"infuse"} generated by the \code{infuse()} function.
#' @param conf_level Numeric. The confidence level for intervals. Defaults to \code{0.95}.
#' @param w Numeric vector. Optional weights for calculating the Non-Prioritized
#'   Outcome (NPO) when multiple outcomes are present. Defaults to equal weighting.
#'
#' @return A tidy \code{data.table} of class \code{c("realise", "data.table", "data.frame")}
#' summarizing each outcome and the combined NPO. It contains the following columns:
#' \itemize{
#'   \item \code{Variable}: The outcome name (or "NPO").
#'   \item \code{Metric}: The specific statistic (Favorable, Unfavorable, Net Treatment Benefit, Win Ratio, or GNNT).
#'   \item \code{Estimate}: The calculated point estimate.
#'   \item \code{Se}: The standard error derived directly from the influence functions.
#'   \item \code{Lower}: Lower bound of the confidence interval.
#'   \item \code{Upper}: Upper bound of the confidence interval.
#'   \item \code{PValue}: Two-sided p-value testing the null hypothesis of no treatment effect (returns \code{NA} for base proportions).
#' }
#'
#' @details
#' \bold{Variance Estimation:} Standard errors are derived asymptotically by computing
#' the sample variance of the patient-level influence functions generated by \code{infuse()}.
#'
#' \bold{Metric-Specific Adjustments:}
#' \itemize{
#'   \item \bold{Win Ratio:} Inference is performed on the logarithmic scale to ensure
#'   normality, and the resulting estimates and bounds are exponentiated back to the original scale.
#'   \item \bold{GNNT (Generalized Number Needed to Treat):} Calculated as the ceiling
#'   of \eqn{1 / \text{Net Benefit}}.
#'   \item \bold{Small Sample Proportions:} For the Favorable and Unfavorable proportion metrics,
#'   if the expected number of events or non-events is small (\eqn{n \times E < 10} or
#'   \eqn{n \times (1 - E) < 10}), a Wilson score interval is automatically applied instead
#'   of a standard Wald interval to guarantee proper coverage.
#' }
#'
#' @examples
#' # ---------------------------------------------------------
#' # Example 1: Survival Data
#' # ---------------------------------------------------------
#' data(ipilimumab)
#' s <- infuse(Surv(time, event)(6, high) ~ arm,
#'             data = ipilimumab,
#'             treated = "ipilimumab")
#'
#' h <- realise(s)
#' print(h)
#'
#' # ---------------------------------------------------------
#' # Example 2: Multiple Outcomes (NPO)
#' # ---------------------------------------------------------
#' data(obstetrics)
#' s <- infuse(PretermYN("Yes") + Birthweight(500, high) ~ Group,
#'             data = obstetrics,
#'             treated = "T")
#'
#' # Realise with equal weights (default)
#' h <- realise(s)
#'
#' # Realise with custom weights (e.g., more weight on PretermYN)
#' h_weighted <- realise(s, w = c(0.7, 0.3))
#'
#' # ---------------------------------------------------------
#' # Example 3: Continuous Data (Obstetrics)
#' # ---------------------------------------------------------
#' data(obstetrics)
#' # High birthweight is "good", 500g margin
#' s <- infuse(Birthweight(500, high) ~ Group,
#'                  data = obstetrics,
#'                  treated = "T")
#'
#' h <- realise(s)
#' print(h)
#'
#' # ---------------------------------------------------------
#' # Example 4: Longitudinal Binary Data (Respiratory)
#' # ---------------------------------------------------------
#' data(respiratory)
#' # We analyze status at the final visit (Visit 4)
#' resp_v4 <- respiratory[respiratory$visit == 4, ]
#' s <- infuse(outcome("Yes") ~ treat,
#'                  data = resp_v4,
#'                  treated = "A")
#'
#' h <- realise(s)
#' print(h)
#'
#' @import data.table
#' @importFrom stats qnorm pnorm
#' @export
realise <- function(s, conf_level = 0.95,w = NULL) {

  Data <- copy(s)

  if (!inherits(s, "infuse")) stop("Input must be a 'infuse' object.")

  # --- 2. Setup Data ---
  n_vars    <- length(Data$metadata$name)
  #zz        <- qnorm(1 - (1 - conf_level) / 2)
  zz <- qt(1 - (1 - conf_level) / 2,dim(Data$data)[1]/n_vars)
  responses <- Data$metadata$name


  ### Add  Non-Prioritized Outcome (NPO) if needed
  if (n_vars >1) {
    ww_vec <- if (is.null(w)) rep(1 / n_vars, n_vars) else w
    wdat   <- data.table(name = responses, ww = ww_vec)
    # 2. Merge weights into DD$data by reference (Zero-copy join)
    Data$data[wdat, on = "name", ww := i.ww]
    # 3. Define the columns to aggregate
    cols_to_agg <- c("f_pe", "f_ifval", "u_pe", "u_ifval")
    # 4. Calculate weighted mean by p_i_d (and arm) using .SD
    npo_data <- Data$data[, lapply(.SD, function(x) sum(x * ww,na.rm=TRUE) / sum(ww,na.rm=TRUE)),
                        by = .(p_i_d, arm),
                        .SDcols = cols_to_agg]
    # Add the 'name' column to the new NPO data
    npo_data[, name := "NPO"]
    # 5. Handle the factor levels for 'name' so rbindlist doesn't conflict
    current_levels <- levels(Data$data$name)
    new_levels <- c(current_levels, "NPO")
    Data$data[, name := factor(name, levels = new_levels)]
    npo_data[, name := factor(name, levels = new_levels)]
    # 6. Bind the new NPO rows back into the main dataset
    Data$data <- rbindlist(list(Data$data, npo_data), use.names = TRUE, fill = TRUE)
    responses <- c(responses,"NPO")
  }


  # --- 3. Individual Outcomes ---
  indiv_df <- Data$data[,`:=`(n_pe = f_pe - u_pe, n_ifval = f_ifval - u_ifval,
                              lw_pe = log(f_pe) - log(u_pe), lw_ifval = f_ifval/f_pe - u_ifval/u_pe)]
  indiv_df <- indiv_df[,.(name,p_i_d,arm,f_pe,f_ifval,u_pe,u_ifval,n_pe,n_ifval,lw_pe,lw_ifval)]


  ## reshape in long format:
  long_df <- melt(
    indiv_df,
    measure.vars = measure(prefix, value.name, pattern = "^(.*)_(pe|ifval)$")
  )


  ## Calculate variances:
  result <- long_df[, .(S2 = sum(1/sum(as.numeric(!is.na(ifval)))^2 * ifval^2, na.rm = TRUE),n = sum(as.numeric(!is.na(ifval)))), by = .(name, arm, prefix,pe)]
  result[, n := sum(n), by = .(name,prefix)]


  ## Calculate standard errors
  wide_result <- dcast(result, name + prefix + pe +n~ arm, value.var = "S2")
  wide_result <- wide_result[, se := sqrt(X + Y)]

  # Calculate Wald stats
  ooo <- wide_result[, `:=`(LB = pe-zz*se, UB = pe+zz*se,PV = 2 * (1 - pnorm(abs(pe/se))))]
  setnames(ooo,c("prefix","name","pe","se"),c("Metric","Variable","E","SE"))
  ooo <- ooo[,.(Variable,Metric,n,E,SE,LB,UB,PV)]

  # --- 5. Post-Processing & Transformations ---
  # 1. Back-transform Win Ratio
  # We subset to only the "lw" rows, and apply exp() to E, LB, and UB
  cols_to_exp <- c("E", "LB", "UB")
  ooo[Metric == "lw", (cols_to_exp) := lapply(.SD, exp), .SDcols = cols_to_exp]

  # 2. GNNT Logic
  # Create the new rows from the "n" metric
  new_rows <- ooo[Metric == "n"]

  # Mutate the new rows
  new_rows[, `:=`(
    Metric = "t",
    LB = ceiling(1 / (E + zz * SE)),
    UB = ceiling(1 / (E - zz * SE)),
    E  = ceiling(1 / E)
  )]

  # Bind the new rows back to the original dataset
  ooo <- rbind(ooo, new_rows)

  # Wilson Adjustment for small proportions
  #ss <- s$metadata[, .(Variable = name, ssx, ssy)]
  idx_prop <- ooo[, Metric %in% c("f", "u")]
  idx_wilson <- ooo[, idx_prop & ((n * E < 10) | (n * (1 - E) < 10))]


  # 2. Update LB and UB ONLY where the Wilson condition is true
  ooo[idx_wilson, `:=`(
    LB = (1/(1+zz^2/n)) * (E + zz^2/(2*n) - zz * sqrt(SE^2 + zz^2/(4*n^2))),
    UB = (1/(1+zz^2/n)) * (E + zz^2/(2*n) + zz * sqrt(SE^2 + zz^2/(4*n^2)))
  )]

  # 3. Update PV to NA ONLY where the prop condition is true
  # Note: NA_real_ is the safer, stricter data.table equivalent to as.numeric(NA)
  ooo[idx_prop, PV := NA_real_]
  ooo <- ooo[,c("n"):=NULL]

  # --- 6. Final Formatting ---
  # 1. Update/Create columns in-place
  final_df <- ooo[, .(
    Variable = factor(Variable, levels = responses),
    Metric   = factor(fcase(
      Metric == "f",  "Favorable",
      Metric == "u",  "Unfavorable",
      Metric == "n",  "Net Treatment Benefit",
      Metric == "lw", "Win Ratio",
      Metric == "t",  "GNNT"
    ), levels = c("Favorable", "Unfavorable", "Net Treatment Benefit", "Win Ratio", "GNNT")),
    Estimate = E,
    Se       = SE,
    Lower    = LB,
    Upper    = UB,
    PValue   = fifelse(PV < 0.001, "<0.001", as.character(round(PV, 3)))
  )]

  # 2. Arrange by Variable and Metric
  setorder(final_df, Variable, Metric)


  structure(final_df, class = c("realise","data.table", "data.frame"))

}
