#' Reap Statistical Inference from Win/Loss Harvest
#'
#' @description
#' Calculates point estimates, standard errors, confidence intervals, and p-values
#' for Win/Loss statistics using Influence Functions. It supports both
#' individual outcome analysis and a weighted Non-Prioritized Outcome (NPO) summary.
#'
#' @param iii An object of class \code{"harvest"} generated by the \code{harvest} function.
#' @param conf_level Numeric. The confidence level for intervals (default 0.95).
#' @param w Numeric vector. Optional weights for calculating the Non-Prioritized
#'   Outcome (NPO). Defaults to equal weighting.
#'
#' @return A tidy data frame summarizing each outcome and the NPO with:
#' \itemize{
#'   \item \code{Variable}: The outcome name (or "NPO").
#'   \item \code{Metric}: Favorable, Unfavorable, Net Benefit, Win Ratio, or NNT.
#'   \item \code{Estimate}: The point estimate.
#'   \item \code{Se}: Standard error derived from Influence Functions.
#'   \item \code{Lower, Upper}: Wald-based confidence intervals.
#'   \item \code{PValue}: Two-sided p-value against the null hypothesis.
#' }
#'
#' @details
#' The inference for the \bold{Win Ratio} is performed on the log-scale and
#' then back-transformed to ensure the confidence interval is strictly positive.
#' The \bold{NNT} is calculated as the ceiling of \eqn{1 / Net Benefit}.
#'
#' @examples
#' # ---------------------------------------------------------
#' # Example 1: Survival Data (Ipilimumab)
#' # ---------------------------------------------------------
#' data(ipilimumab)
#' # Higher time is "good" for Progression-Free Survival
#' fit <- sow(Surv(time, event) ~ arm,
#'                  data = ipilimumab,
#'                  treated = "ipilimumab",
#'                  good = "high")
#'
#' harvest(fit,lambda = 6) %>% reap()
#'
#' # ---------------------------------------------------------
#' # Example 2: Continuous Data (Obstetrics)
#' # ---------------------------------------------------------
#' data(obstetrics)
#' # High birthweight is generally considered "good"
#' fit <- sow(Birthweight ~ Group,
#'                 data = obstetrics,
#'                 treated = "T",
#'                 good = "high")
#'
#' h <- harvest(fit,lambda = 500) %>% reap()
#' print(h)
#'
#' # ---------------------------------------------------------
#' # Example 3: Longitudinal Binary Data (Respiratory)
#' # ---------------------------------------------------------
#' data(respiratory)
#' # We analyze status at the final visit (Visit 4)
#' resp_v4 <- respiratory[respiratory$visit == 4, ]
#' sown_resp <- sow(outcome ~ treat,
#'                  data = resp_v4,
#'                  treated = "A",
#'                  good = "high")
#'
#' h <- harvest(fit,lambda = 0.5) %>% reap()
#' print(h)
#'
#' # ---------------------------------------------------------
#' # Example 4: Multiple Outcomes (Epilepsy)
#' # ---------------------------------------------------------
#' data(epilepsy)
#' # Looking at seizure rate at Period 4. Lower rate is "good".
#' epi_v4 <- epilepsy[epilepsy$period == 4, ]
#' sown_epi <- sow(seizure.rate ~ treatment,
#'                 data = epi_v4,
#'                 treated = "Progabide",
#'                 good = "low")
#'
#' h <- harvest(fit,lambda = 15) %>% reap()
#' print(h)
#'
#' @export
reap <- function(iii, conf_level = 0.95,w = NULL) {

  types_map <- attr(iii, "var_types")

  # --- 1. Setup & Metadata ---
  n_vars <- length(iii$theta$Variable)
  alp       <- 1 - conf_level
  zz        <- qnorm(1 - alp / 2)
  responses <- iii$theta$Variable

  IF_x <- iii$IF_x %>% mutate(XY="x")
  IF_y <- iii$IF_y %>% mutate(XY="y")
  PE <- iii$theta

  IF <- rbind(IF_x,IF_y)

  #######################
  ### Set up NPO outcome
  #######################
  ww_vec <- if (is.null(w)) rep(1 / n_vars, n_vars) else w
  wdat   <- data.frame(Variable = responses, ww = ww_vec)

  ooo0 <- IF %>% left_join(wdat,by="Variable") %>%
    pivot_longer(f:w) %>%
    mutate(tt = sqrt(weights) * value *ww) %>%
    group_by(ID,name,XY) %>%
    summarise(iiff = sum(tt,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
    mutate(Variable ="NPO")

  nn0 <- IF %>%
    group_by(ID,XY) %>%
    summarise(c = prod(ce,na.rm=TRUE),.groups = "drop" ) %>%
    group_by(XY) %>%
    summarise(n = sum(c,na.rm=TRUE),.groups = "drop") %>%
    mutate(Variable ="NPO") %>%
    pivot_wider(names_from = XY,values_from = n,names_prefix = "n")

  pe0 <- PE %>% left_join(wdat,by="Variable") %>%
    pivot_longer(f:w) %>%
    group_by(name) %>%
    summarise(pe = sum(ww*value,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
    mutate(Variable = "NPO")


  ################################
  ### Set up rest of the outcomes
  ################################
  ooo1 <- IF %>% pivot_longer(f:w) %>%
    mutate(iiff = value*sqrt(weights)) %>%
    select(ID,name,XY,iiff,Variable)

  nn1 <- IF %>%
    group_by(Variable,XY) %>%
    summarise(n = sum(ce,na.rm=TRUE),.groups = "drop") %>%
    pivot_wider(names_from = XY,values_from = n,names_prefix = "n")

  pe1 <- PE %>% pivot_longer(f:w,values_to = "pe")

  #################
  ### Put together
  #################
  ooo <- rbind(ooo1,ooo0)

  nn <- rbind(nn1,nn0)

  pe <- rbind(pe1,pe0)


  ###########################
  ### Make core calculations
  ###########################
  ooo <- ooo  %>%
    mutate(if2 = iiff^2) %>%
    group_by(Variable,name,XY) %>%
    summarise(tau = sum(if2,na.rm=TRUE),.groups = "drop") %>%
    pivot_wider(names_from = XY,values_from = tau,names_prefix = "tau")

  ooo <- ooo %>% left_join(nn,by="Variable") %>% left_join(pe,by=c("Variable","name"))

  ooo <- ooo %>%
    mutate(se = sqrt(taux/nx + tauy/ny)) %>%
    mutate(E=pe,
           LB = pe - zz * se,
           UB = pe + zz * se,
           PV = 2 * (1 - pnorm(abs(pe/se))))


  ######################
  ### Correct Win Ratio
  ######################
  ooo <- ooo %>%
    mutate(E = if_else(name == "w",exp(E),E),
           LB = if_else(name == "w",exp(LB),LB),
           UB = if_else(name == "w",exp(UB),UB))

  ################
  ### Create GNNT
  ################
  dd <- ooo %>%
    filter(name == "n") %>% mutate(name = "t") %>%
    mutate(E = ceiling(1/pe),
           LB = ceiling(1 / ( pe + zz * se ) ),
           UB = ceiling(1 / ( pe - zz * se) ))
  ooo <- rbind(ooo,dd)



  ######################
  ### Final adjustments
  ######################
  responses <- c(responses,"NPO")

  ooo <- ooo %>%
    mutate(Metric = case_when(name == "f"~"Favorable",
                              name == "u"~"Unfavorable",
                              name == "n"~"Net Treatment Benefit",
                              name == "w"~"Win Ratio",
                              name == "t"~"GNNT"))

  ooo <- ooo %>% select(Variable,Metric,Estimate=E,Se = se,Lower = LB, Upper= UB,PValue = PV)

  ooo <- ooo %>% mutate(PValue = if_else(PValue<0.001,"<0.001",as.character(round(PValue,3))))

  ooo <- ooo %>%
    mutate(Variable = ordered(Variable,levels = responses)) %>%
    mutate(Metric = ordered(Metric,levels = c("Favorable","Unfavorable","Net Treatment Benefit","Win Ratio","GNNT")))

  ooo %>% arrange(Variable,Metric)


  }
