#' Reap Statistical Inference from Win/Loss Harvest
#'
#' @description
#' Calculates point estimates, standard errors, confidence intervals, and p-values
#' for Win/Loss statistics using Influence Functions. It supports both
#' individual outcome analysis and a weighted Non-Prioritized Outcome (NPO) summary.
#'
#' @param iii An object of class \code{"harvest"} generated by the \code{harvest} function.
#' @param conf_level Numeric. The confidence level for intervals (default 0.95).
#' @param w Numeric vector. Optional weights for calculating the Non-Prioritized
#'   Outcome (NPO). Defaults to equal weighting.
#'
#' @return A tidy data frame summarizing each outcome and the NPO with:
#' \itemize{
#'   \item \code{Variable}: The outcome name (or "NPO").
#'   \item \code{Metric}: Favorable, Unfavorable, Net Benefit, Win Ratio, or NNT.
#'   \item \code{Estimate}: The point estimate.
#'   \item \code{Se}: Standard error derived from Influence Functions.
#'   \item \code{Lower, Upper}: Wald-based confidence intervals.
#'   \item \code{PValue}: Two-sided p-value against the null hypothesis.
#' }
#'
#' @details
#' The inference for the \bold{Win Ratio} is performed on the log-scale and
#' then back-transformed to ensure the confidence interval is strictly positive.
#' The \bold{NNT} is calculated as the ceiling of \eqn{1 / Net Benefit}.
#'
#' @examples
#' # ---------------------------------------------------------
#' # Example 1: Survival Data (Ipilimumab)
#' # ---------------------------------------------------------
#' data(ipilimumab)
#' # Higher time is "good" for Progression-Free Survival
#' fit <- sow(Surv(time, event) ~ arm,
#'                  data = ipilimumab,
#'                  treated = "ipilimumab",
#'                  good = "high")
#'
#' harvest(fit,lambda = 6) %>% reap()
#'
#' # ---------------------------------------------------------
#' # Example 2: Continuous Data (Obstetrics)
#' # ---------------------------------------------------------
#' data(obstetrics)
#' # High birthweight is generally considered "good"
#' fit <- sow(Birthweight ~ Group,
#'                 data = obstetrics,
#'                 treated = "T",
#'                 good = "high")
#'
#' h <- harvest(fit,lambda = 500) %>% reap()
#' print(h)
#'
#' # ---------------------------------------------------------
#' # Example 3: Longitudinal Binary Data (Respiratory)
#' # ---------------------------------------------------------
#' data(respiratory)
#' # We analyze status at the final visit (Visit 4)
#' resp_v4 <- respiratory[respiratory$visit == 4, ]
#' sown_resp <- sow(outcome ~ treat,
#'                  data = resp_v4,
#'                  treated = "A",
#'                  good = "high")
#'
#' h <- harvest(fit,lambda = 0.5) %>% reap()
#' print(h)
#'
#' # ---------------------------------------------------------
#' # Example 4: Multiple Outcomes (Epilepsy)
#' # ---------------------------------------------------------
#' data(epilepsy)
#' # Looking at seizure rate at Period 4. Lower rate is "good".
#' epi_v4 <- epilepsy[epilepsy$period == 4, ]
#' sown_epi <- sow(seizure.rate ~ treatment,
#'                 data = epi_v4,
#'                 treated = "Progabide",
#'                 good = "low")
#'
#' h <- harvest(fit,lambda = 15) %>% reap()
#' print(h)
#'
#' @export
reap <- function(iii, conf_level = 0.95,w = NULL) {

  # --- 1. Setup & Metadata ---
  n_vars <- length(iii$theta$Variable)
  alp       <- 1 - conf_level
  zz        <- qnorm(1 - alp / 2)
  responses <- iii$theta$Variable

  IF_x <- iii$IF_x
  IF_y <- iii$IF_y
  PE <- iii$theta

  temp <- lapply(responses,function(xxx){

    ifx <- IF_x %>% filter(Variable==xxx) #%>% select(xweights,ce,f)
    ify <- IF_y %>% filter(Variable==xxx) #%>% select(yweights,ce,f)
    pe <- PE %>% filter(Variable==xxx) #%>% pull(f)
    #nx <- sum(!is.na(ifx$ce),na.rm=TRUE)
    #ny <- sum(!is.na(ify$ce),na.rm=TRUE)
    nx <- sum(ifx$ce,na.rm=TRUE)
    ny <- sum(ify$ce,na.rm=TRUE)
    #nx<-1
    #ny<-1
    wx <- ifx$xweights
    wy <- ify$yweights

    ## FAVORABLE
    #taux <- c_mean(ifx$f^2,ifx$ce)
    #tauy <- c_mean(ify$f^2,ifx$ce)
    taux <- sum(ifx$f^2 * wx,na.rm=TRUE)
    tauy <- sum(ify$f^2 * wy,na.rm=TRUE)
    se <- sqrt(taux/nx + tauy/ny)
    fff <- data.frame(Variable=xxx,E=pe$f,SE=se,
                         LB = pe$f - zz * se,
                         UB = pe$f + zz * se,
                      PV = 2 * (1 - pnorm(abs(pe$f/se))),
                         Metric = "Favorable")

    ## UNFAVORABLE
    #taux <- c_mean(ifx$u^2,ifx$ce)
    #tauy <- c_mean(ify$u^2,ifx$ce)
    taux <- sum(ifx$u^2 * wx,na.rm=TRUE)
    tauy <- sum(ify$u^2 * wy,na.rm=TRUE)
    se <- sqrt(taux/nx + tauy/ny)
    uuu <- data.frame(Variable=xxx,E=pe$u,SE=se,
                         LB = pe$u - zz * se,
                         UB = pe$u + zz * se,
                      PV = 2 * (1 - pnorm(abs(pe$u/se))),
                         Metric = "Unfavorable")


    ## NET BENEFIT
    #taux <- c_mean(ifx$n^2,ifx$ce)
    #tauy <- c_mean(ify$n^2,ifx$ce)
    taux <- sum(ifx$n^2 * wx,na.rm=TRUE)
    tauy <- sum(ify$n^2 * wy,na.rm=TRUE)
    se <- sqrt(taux/nx + tauy/ny)
    nnn <- data.frame(Variable=xxx,E=pe$n,SE=se,
                         LB = pe$n - zz * se,
                         UB = pe$n + zz * se,
                      PV = 2 * (1 - pnorm(abs(pe$n/se))),
                         Metric = "NetT Benefit")

    ## WIN RATIO
    #taux <- c_mean(ifx$w^2,ifx$ce)
    #tauy <- c_mean(ify$w^2,ifx$ce)
    taux <- sum(ifx$w^2 * wx,na.rm=TRUE)
    tauy <- sum(ify$w^2 * wy,na.rm=TRUE)
    se <- sqrt(taux/nx + tauy/ny)
    www <- data.frame(Variable=xxx,E=exp(pe$w),SE=se,
                         LB = exp( pe$w - zz * se ),
                         UB = exp(pe$w + zz * se) ,
                      PV = 2 * (1 - pnorm(abs(pe$w/se))),
                         Metric = "Win Ratio")

    ## NNT
    #taux <- c_mean(ifx$n^2,ifx$ce)
    #tauy <- c_mean(ify$n^2,ifx$ce)
    taux <- sum(ifx$n^2 * wx,na.rm=TRUE)
    tauy <- sum(ify$n^2 * wy,na.rm=TRUE)
    se <- sqrt(taux/nx + tauy/ny)
    ttt <- data.frame(Variable=xxx,E=ceiling(1/pe$n),SE=se,
                         LB = ceiling(1/( pe$n + zz * se ) ),
                         UB = ceiling(1/(pe$n - zz * se) ),
                      PV = 2 * (1 - pnorm(abs(pe$n/se))),
                         Metric = "NNT" )

    rbind(fff,uuu,nnn,www,ttt)
  })

  ooo <- do.call("rbind",temp)


  # Prepare weight mapping
  if (n_vars>1) {
    ww_vec <- if (is.null(w)) rep(1 / n_vars, n_vars) else w
    wdat   <- data.frame(Variable = responses, ww = ww_vec)
    pe <- iii$theta %>% left_join(wdat,by="Variable")
    ifx <- iii$IF_x %>% left_join(wdat,by="Variable")
    ify <- iii$IF_y %>% left_join(wdat,by="Variable")

    ifx <- ifx %>% mutate(ww = if_else(is.na(ce),NA,ww))
    ify <- ify %>% mutate(ww = if_else(is.na(ce),NA,ww))

    pe <- pe %>% pivot_longer(f:w)
    pe <- pe %>%
      group_by(name) %>%
      summarise(value = sum(ww*value,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
      pivot_wider(names_from = name,values_from = value)%>%
      mutate(Variable = "NPO")

    nx <- ifx %>% group_by(ID) %>% summarise(c = prod(ce,na.rm=TRUE),.groups = "drop" ) %>%
      summarise(o = sum(c,na.rm=TRUE),.groups = "drop") %>% pull(o)
    ny <- ify %>% group_by(ID) %>% summarise(c = prod(ce,na.rm=TRUE),.groups = "drop" ) %>%
      summarise(o = sum(c,na.rm=TRUE),.groups = "drop") %>% pull(o)

    nx <- 1
    ny <- 1


        ## FAVORABLE
    #taux <- c_mean(ifx$f^2,ifx$ce)
    #tauy <- c_mean(ify$f^2,ifx$ce)
    taux <- ifx %>%
      mutate(temp = xweights*f*ww) %>% group_by(ID) %>%
      summarise(tt = sum(temp,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
      summarise(o = sum(tt^2),.groups = "drop") %>% pull(o)
    tauy <- ify %>%
      mutate(temp = yweights*f*ww) %>% group_by(ID) %>%
      summarise(tt = sum(temp,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
      summarise(o = sum(tt^2),.groups = "drop") %>% pull(o)
    se <- sqrt(taux/nx + tauy/ny)
    fff <- data.frame(Variable="NPO",E=pe$f,SE=se,
                      LB = pe$f - zz * se,
                      UB = pe$f + zz * se,
                      PV = 2 * (1 - pnorm(abs(pe$f/se))),
                      Metric = "Favorable")

    ## UNFAVORABLE
    taux <- ifx %>%
      mutate(temp = xweights*u*ww) %>% group_by(ID) %>%
      summarise(tt = sum(temp,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
      summarise(o = sum(tt^2),.groups = "drop") %>% pull(o)
    tauy <- ify %>%
      mutate(temp = yweights*u*ww) %>% group_by(ID) %>%
      summarise(tt = sum(temp,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
      summarise(o = sum(tt^2),.groups = "drop") %>% pull(o)
    se <- sqrt(taux/nx + tauy/ny)
    uuu <- data.frame(Variable="NPO",E=pe$u,SE=se,
                      LB = pe$u - zz * se,
                      UB = pe$u + zz * se,
                      PV = 2 * (1 - pnorm(abs(pe$u/se))),
                      Metric = "Unfavorable")


    ## NET BENEFIT
    taux <- ifx %>%
      mutate(temp = xweights*n*ww) %>% group_by(ID) %>%
      summarise(tt = sum(temp,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
      summarise(o = sum(tt^2),.groups = "drop") %>% pull(o)
    tauy <- ify %>%
      mutate(temp = yweights*n*ww) %>% group_by(ID) %>%
      summarise(tt = sum(temp,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
      summarise(o = sum(tt^2),.groups = "drop") %>% pull(o)
    se <- sqrt(taux/nx + tauy/ny)
    nnn <- data.frame(Variable="NPO",E=pe$n,SE=se,
                      LB = pe$n - zz * se,
                      UB = pe$n + zz * se,
                      PV = 2 * (1 - pnorm(abs(pe$n/se))),
                      Metric = "NetT Benefit")

    ## WIN RATIO
    taux <- ifx %>%
      mutate(temp = xweights*w*ww) %>% group_by(ID) %>%
      summarise(tt = sum(temp,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
      summarise(o = sum(tt^2),.groups = "drop") %>% pull(o)
    tauy <- ify %>%
      mutate(temp = yweights*w*ww) %>% group_by(ID) %>%
      summarise(tt = sum(temp,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
      summarise(o = sum(tt^2),.groups = "drop") %>% pull(o)
    se <- sqrt(taux/nx + tauy/ny)
    www <- data.frame(Variable="NPO",E=exp(pe$w),SE=se,
                      LB = exp( pe$w - zz * se ),
                      UB = exp(pe$w + zz * se) ,
                      PV = 2 * (1 - pnorm(abs(pe$w/se))),
                      Metric = "Win Ratio")

    ## NNT
    taux <- ifx %>%
      mutate(temp = xweights*n*ww) %>% group_by(ID) %>%
      summarise(tt = sum(temp,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
      summarise(o = sum(tt^2),.groups = "drop") %>% pull(o)
    tauy <- ify %>%
      mutate(temp = yweights*n*ww) %>% group_by(ID) %>%
      summarise(tt = sum(temp,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
      summarise(o = sum(tt^2),.groups = "drop") %>% pull(o)
    se <- sqrt(taux/nx + tauy/ny)
    ttt <- data.frame(Variable="NPO",E=ceiling(1/pe$n),SE=se,
                      LB = ceiling(1/( pe$n + zz * se ) ),
                      UB = ceiling(1/(pe$n - zz * se) ),
                      PV = 2 * (1 - pnorm(abs(pe$n/se))),
                      Metric = "NNT" )

    ooo <- rbind(ooo,rbind(fff,uuu,nnn,www,ttt))




    #ifx <- ifx %>%
    #  group_by(ID,name) %>%
    #  summarise(value = sum(ww*value,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop",
    #            ce = min(ce,na.rm=TRUE)) %>%
    #  pivot_wider(names_from = name,values_from = value) %>%
    #  mutate(Variable = "NPO")

    #ify <- ify %>% pivot_longer(yweights:w)
    #ify <- ify %>%
    #  group_by(ID,name) %>%
    #  summarise(value = sum(ww*value,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop",
    #            ce = min(ce,na.rm=TRUE)) %>%
    #  pivot_wider(names_from = name,values_from = value)%>%
    #  mutate(Variable = "NPO")

    #pe <- pe %>% pivot_longer(f:w)
    #pe <- pe %>%
    #  group_by(name) %>%
    #  summarise(value = sum(ww*value,na.rm=TRUE)/sum(ww,na.rm=TRUE),.groups = "drop") %>%
    #  pivot_wider(names_from = name,values_from = value)%>%
    #  mutate(Variable = "NPO")


    #IF_x <- rbind(IF_x,ifx)
    #IF_y <- rbind(IF_y,ify)
    #PE <- rbind(PE,pe)

    responses <- c(responses,"NPO")
  }


  ooo <- ooo %>% select(Variable,Metric,Estimate=E,Se = SE,Lower = LB, Upper= UB,PValue = PV)

  ooo <- ooo %>% mutate(PValue = if_else(PValue<0.001,"<0.001",as.character(round(PValue,3))))

  ooo <- ooo %>%
    mutate(Variable = ordered(Variable,levels = responses)) %>%
    mutate(Metric = ordered(Metric,levels = c("Favorable","Unfavorable","NetT Benefit","Win Ratio","NNT")))

  ooo %>% arrange(Variable,Metric)

  }
