#' Reap Statistical Inference from Win/Loss Harvest
#'
#' @description
#' Calculates point estimates, standard errors, confidence intervals, and p-values
#' for Win/Loss statistics using Influence Functions. It supports both
#' individual outcome analysis and a weighted Non-Prioritized Outcome (NPO) summary.
#'
#' @param iii An object of class \code{"harvest"} generated by the \code{harvest} function.
#' @param conf_level Numeric. The confidence level for intervals (default 0.95).
#' @param w Numeric vector. Optional weights for calculating the Non-Prioritized
#'   Outcome (NPO). Defaults to equal weighting.
#'
#' @return A tidy data frame of class \code{c("reap", "data.frame")} summarizing each
#'   outcome and the NPO with:
#' \itemize{
#'   \item \code{Variable}: The outcome name (or "NPO").
#'   \item \code{Metric}: Favorable, Unfavorable, Net Benefit, Win Ratio, or GNNT.
#'   \item \code{Estimate}: The point estimate.
#'   \item \code{Se}: Standard error derived from Influence Functions.
#'   \item \code{Lower, Upper}: Wald-based or Wilson-adjusted confidence intervals.
#'   \item \code{PValue}: Two-sided p-value against the null hypothesis (or NA for proportions).
#' }
#'
#' @details
#' The inference for the \bold{Win Ratio} is performed on the log-scale and
#' then back-transformed. The \bold{GNNT} (Generalized Number Needed to Treat)
#' is calculated as the ceiling of \eqn{1 / Net Benefit}. For small sample sizes
#' in Favorable/Unfavorable proportions, a Wilson-adjusted interval is used.
#'
#' @examples
#' # ---------------------------------------------------------
#' # Example 1: Survival Data (Ipilimumab)
#' # ---------------------------------------------------------
#' data(ipilimumab)
#' # Higher time is "good" for Progression-Free Survival
#' s <- sow(Surv(time, event) ~ arm,
#'                  data = ipilimumab,
#'                  treated = "ipilimumab",
#'                  good = "high")
#'
#' harvest(s,lambda = 6) %>% reap()
#'
#' # ---------------------------------------------------------
#' # Example 2: Continuous Data (Obstetrics)
#' # ---------------------------------------------------------
#' data(obstetrics)
#' # High birthweight is generally considered "good"
#' s <- sow(Birthweight ~ Group,
#'                 data = obstetrics,
#'                 treated = "T",
#'                 good = "high")
#'
#' h <- harvest(s,lambda = 500) %>% reap()
#' print(h)
#'
#' # ---------------------------------------------------------
#' # Example 3: Longitudinal Binary Data (Respiratory)
#' # ---------------------------------------------------------
#' data(respiratory)
#' # We analyze status at the final visit (Visit 4)
#' resp_v4 <- respiratory[respiratory$visit == 4, ]
#' s <- sow(outcome ~ treat,
#'                  data = resp_v4,
#'                  treated = "A",
#'                  good = "high")
#'
#' h <- harvest(s,lambda = 0.5) %>% reap()
#' print(h)
#'
#' # ---------------------------------------------------------
#' # Example 4: Multiple Outcomes (Epilepsy)
#' # ---------------------------------------------------------
#' data(epilepsy)
#' # Looking at seizure rate at Period 4. Lower rate is "good".
#' epi_v4 <- epilepsy[epilepsy$period == 4, ]
#' s <- sow(seizure.rate ~ treatment,
#'                 data = epi_v4,
#'                 treated = "Progabide",
#'                 good = "low")
#'
#' h <- harvest(s,lambda = 15) %>% reap()
#' print(h)
#'
#' @export
reap <- function(iii, conf_level = 0.95,w = NULL) {

  if (!inherits(iii, "harvest")) stop("Input must be a 'harvest' object.")

  # --- 1. Internal Helper for Inference ---
  compute_stats <- function(df, zz, var_label) {
    # Aggregate point estimates
    poes <- df %>%
      select(f_pe, u_pe, n_pe, lw_pe) %>%
      distinct() %>%
      tidyr::pivot_longer(everything(), names_to = "Metric", values_to = "pe") %>%
      mutate(Metric = stringr::str_remove(Metric, "_pe"))

    # Aggregate sample sizes
    sasi <- df %>%
      group_by(XY) %>%
      summarise(n = sum(ce, na.rm = TRUE), .groups = "drop") %>%
      tidyr::pivot_wider(names_from = XY, values_from = n, names_prefix = "n")

    # Aggregate standard errors (Influence Functions)
    eser <- df %>%
      select(ID, weights, XY, f_if, u_if, n_if, lw_if) %>%
      tidyr::pivot_longer(f_if:lw_if, names_to = "Metric", values_to = "infl") %>%
      mutate(Metric = stringr::str_remove(Metric, "_if")) %>%
      group_by(Metric, XY) %>%
      summarise(tau = sum(weights * infl^2, na.rm = TRUE), .groups = "drop") %>%
      tidyr::pivot_wider(names_from = XY, values_from = tau, names_prefix = "tau")

    # Combine and calculate Wald stats
    poes %>%
      inner_join(eser, by = "Metric") %>%
      bind_cols(sasi) %>%
      mutate(
        Variable = var_label,
        se = sqrt(taux/nx + tauy/ny),
        E  = pe,
        LB = pe - zz * se,
        UB = pe + zz * se,
        PV = 2 * (1 - pnorm(abs(pe/se)))
      )
  }

  # --- 2. Setup Data ---
  n_vars    <- length(iii$theta$Variable)
  zz        <- qnorm(1 - (1 - conf_level) / 2)
  responses <- iii$theta$Variable

  PE <- iii$theta %>% select(Variable, A = f, B = u)
  IF <- bind_rows(mutate(iii$IF_x, XY = "x"), mutate(iii$IF_y, XY = "y")) %>%
    select(Variable, XY, ID:weights, IF_A = f, IF_B = u) %>%
    left_join(PE, by = "Variable") %>%
    mutate(weights = round(weights, 16))

  # --- 3. Individual Outcomes ---
  indiv_df <- IF %>%
    mutate(
      f_pe = A, f_if = IF_A,
      u_pe = B, u_if = IF_B,
      n_pe = A - B, n_if = IF_A - IF_B,
      lw_pe = log(A) - log(B), lw_if = IF_A/A - IF_B/B
    )

  results_list <- lapply(responses, function(v) {
    compute_stats(filter(indiv_df, Variable == v), zz, v)
  })
  ooo <- bind_rows(results_list)

  # --- 4. Non-Prioritized Outcome (NPO) ---
  if (n_vars > 1) {
    ww_vec <- if (is.null(w)) rep(1 / n_vars, n_vars) else w
    wdat   <- data.frame(Variable = responses, ww = ww_vec)

    npo_prep <- IF %>%
      left_join(wdat, by = "Variable") %>%
      mutate(ww = if_else(is.na(ce), as.numeric(NA), ww))

    As <- npo_prep %>% select(Variable, A, ww) %>% distinct() %>% summarise(t = sum(A*ww,na.rm=TRUE)) %>% pull(t)
    Bs <- npo_prep %>% select(Variable, B, ww) %>% distinct() %>% summarise(t = sum(B*ww,na.rm=TRUE)) %>% pull(t)

    npo_df <- npo_prep %>%
      group_by(ID, XY) %>%
      summarise(
        ce      = prod(ce, na.rm = TRUE), # Logic for NPO sample size
        weights = first(weights),
        f_pe = As, f_if = sum(IF_A * ww, na.rm = TRUE) / sum(ww, na.rm = TRUE),
        u_pe = Bs, u_if = sum(IF_B * ww, na.rm = TRUE) / sum(ww, na.rm = TRUE),
        n_pe = As - Bs, n_if = sum((IF_A - IF_B) * ww, na.rm = TRUE) / sum(ww, na.rm = TRUE),
        lw_pe = log(As) - log(Bs),
        lw_if = sum((IF_A*Bs/(As*Bs) - IF_B*As/(As*Bs)) * ww, na.rm = TRUE) / sum(ww, na.rm = TRUE),
        .groups = "drop"
      )

    ooo <- bind_rows(ooo, compute_stats(npo_df, zz, "NPO"))
    responses <- c(responses, "NPO")
  }

  # --- 5. Post-Processing & Transformations ---
  ooo <- ooo %>%
    # Back-transform Win Ratio
    mutate(
      across(c(E, LB, UB), ~ if_else(Metric == "lw", exp(.x), .x))
    ) %>%
    # GNNT Logic
    bind_rows(
      filter(., Metric == "n") %>%
        mutate(
          Metric = "t",
          E  = ceiling(1/pe),
          LB = ceiling(1 / (pe + zz * se)),
          UB = ceiling(1 / (pe - zz * se))
        )
    )

  # Wilson Adjustment for small proportions
  ooo <- ooo %>%
    mutate(
      wher_prop = Metric %in% c("f", "u"),
      wher_small = (nx * pe < 10) | (nx * (1 - pe) < 10),
      use_wilson = wher_prop & wher_small,
      LB = if_else(use_wilson, (1/(1+zz^2/nx)) * (pe + zz^2/(2*nx) - zz * sqrt(se^2 + zz^2/(4*nx^2))), LB),
      UB = if_else(use_wilson, (1/(1+zz^2/nx)) * (pe + zz^2/(2*nx) + zz * sqrt(se^2 + zz^2/(4*nx^2))), UB),
      PV = if_else(wher_prop, as.numeric(NA), PV)
    )

  # --- 6. Final Formatting ---
  final_df <- ooo %>%
    mutate(
      Metric = case_when(
        Metric == "f"  ~ "Favorable",
        Metric == "u"  ~ "Unfavorable",
        Metric == "n"  ~ "Net Treatment Benefit",
        Metric == "lw" ~ "Win Ratio",
        Metric == "t"  ~ "GNNT"
      ),
      PValue = if_else(PV < 0.001, "<0.001", as.character(round(PV, 3))),
      Variable = ordered(Variable, levels = responses),
      Metric   = ordered(Metric, levels = c("Favorable", "Unfavorable", "Net Treatment Benefit", "Win Ratio", "GNNT"))
    ) %>%
    select(Variable, Metric, Estimate = E, Se = se, Lower = LB, Upper = UB, PValue) %>%
    arrange(Variable, Metric)

  structure(final_df, class = c("reap", "data.frame"))

  }
